### PR TITLE
Use IAMPrefix() for hostedzone

### LINKED ISSUE #8359: Partition "aws" is not valid for resource "arn:aws:route53:::hostedzone/xxxxxxxxxxxxxx" in us-gov-west-1 region
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Version 1.15.0 (git-9992b4055)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.14

**3. What cloud provider are you using?**

AWS Govcloud

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
```
export CLUSTER_NAME="mission.control"
export AMI_NAME="414987029474/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16"
kops create cluster --image=${AMI_NAME} --dns=private --zones=us-gov-west-1a --name=${CLUSTER_NAME}
```

**5. What happened after the commands executed?**

W0116 21:06:48.637367   15823 executor.go:130] error running task "IAMRolePolicy/masters.mission.control" (5m59s remaining to succeed): error creating/updating IAMRolePolicy: MalformedPolicyDocument: Partition "aws" is not valid for resource "arn:aws:route53:::hostedzone/xxxxxxxxxxxxxx".
	status code: 400, request id: 724f2a61-375c-49f5-952e-110372e0c12d

**6. What did you expect to happen?**

The cluster is created.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-01-17T05:01:42Z"
  name: mission.control
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://mission-control-state-store/mission.control
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-gov-west-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-gov-west-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.15.6
  masterPublicName: api.mission.control
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-gov-west-1a
    type: Public
    zone: us-gov-west-1a
  topology:
    dns:
      type: Private
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-01-17T05:01:43Z"
  labels:
    kops.k8s.io/cluster: mission.control
  name: master-us-gov-west-1a
spec:
  image: 414987029474/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: m3.medium
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-gov-west-1a
  role: Master
  subnets:
  - us-gov-west-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2020-01-17T05:01:43Z"
  labels:
    kops.k8s.io/cluster: mission.control
  name: nodes
spec:
  image: 414987029474/k8s-1.14-debian-stretch-amd64-hvm-ebs-2019-08-16
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-gov-west-1a
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

Looks like this is the relevant JSON for the policy failure

```
    {
      "Effect": "Allow",
      "Action": [
        "route53:ChangeResourceRecordSets",
        "route53:ListResourceRecordSets",
        "route53:GetHostedZone"
      ],
      "Resource": [
        "arn:aws:route53:::hostedzone/xxxxxxxxxxxxxx"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "route53:GetChange"
      ],
      "Resource": [
        "arn:aws:route53:::change/*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "route53:ListHostedZones"
      ],
      "Resource": [
        "*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "ecr:GetAuthorizationToken",
        "ecr:BatchCheckLayerAvailability",
        "ecr:GetDownloadUrlForLayer",
        "ecr:GetRepositoryPolicy",
        "ecr:DescribeRepositories",
        "ecr:ListImages",
        "ecr:BatchGetImage"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}
```

**9. Anything else do we need to know?**

This looks similar to #6763

### PR DESCRIPTION
**Pull request by lazzarello**
fixes #8359 upstream

Tested in us-gov-west-1 zone with the following

```
$ ./kops create cluster --image=${AMI_NAME} --dns=private --zones=us-gov-west-1a --name=${CLUSTER_NAME}
$ ./kops update cluster ${CLUSTER_NAME} --yes
I0117 13:59:21.485847   14570 dns.go:94] Private DNS: skipping DNS validation
I0117 13:59:22.071985   14570 executor.go:103] Tasks: 0 done / 87 total; 44 can run
I0117 13:59:22.751585   14570 vfs_castore.go:675] Issuing new certificate: "apiserver-aggregator-ca"
I0117 13:59:22.828018   14570 vfs_castore.go:675] Issuing new certificate: "etcd-peers-ca-main"
I0117 13:59:22.830881   14570 vfs_castore.go:675] Issuing new certificate: "ca"
I0117 13:59:22.835241   14570 vfs_castore.go:675] Issuing new certificate: "etcd-manager-ca-main"
I0117 13:59:22.911223   14570 vfs_castore.go:675] Issuing new certificate: "etcd-manager-ca-events"
I0117 13:59:22.958590   14570 vfs_castore.go:675] Issuing new certificate: "etcd-peers-ca-events"
I0117 13:59:22.986829   14570 vfs_castore.go:675] Issuing new certificate: "etcd-clients-ca"
I0117 13:59:23.555176   14570 executor.go:103] Tasks: 44 done / 87 total; 23 can run
I0117 13:59:24.182575   14570 vfs_castore.go:675] Issuing new certificate: "apiserver-aggregator"
I0117 13:59:24.419804   14570 vfs_castore.go:675] Issuing new certificate: "kube-controller-manager"
I0117 13:59:24.429200   14570 vfs_castore.go:675] Issuing new certificate: "kube-scheduler"
I0117 13:59:24.435082   14570 vfs_castore.go:675] Issuing new certificate: "kubecfg"
I0117 13:59:24.459443   14570 vfs_castore.go:675] Issuing new certificate: "kops"
I0117 13:59:24.605755   14570 vfs_castore.go:675] Issuing new certificate: "apiserver-proxy-client"
I0117 13:59:24.744055   14570 vfs_castore.go:675] Issuing new certificate: "master"
I0117 13:59:24.783516   14570 vfs_castore.go:675] Issuing new certificate: "kubelet"
I0117 13:59:24.788647   14570 vfs_castore.go:675] Issuing new certificate: "kube-proxy"
I0117 13:59:24.800117   14570 vfs_castore.go:675] Issuing new certificate: "kubelet-api"
I0117 13:59:25.224904   14570 executor.go:103] Tasks: 67 done / 87 total; 18 can run
I0117 13:59:25.622946   14570 launchconfiguration.go:375] waiting for IAM instance profile "nodes.mission.control" to be ready
I0117 13:59:25.643104   14570 launchconfiguration.go:375] waiting for IAM instance profile "masters.mission.control" to be ready
I0117 13:59:36.227543   14570 executor.go:103] Tasks: 85 done / 87 total; 2 can run
I0117 13:59:37.000449   14570 executor.go:103] Tasks: 87 done / 87 total; 0 can run
I0117 13:59:37.000531   14570 dns.go:155] Pre-creating DNS records
I0117 13:59:37.603519   14570 update_cluster.go:305] Exporting kubecfg for cluster
W0117 13:59:37.843630   14570 create_kubecfg.go:76] Did not find API endpoint for gossip hostname; may not be able to reach cluster
kops has set your kubectl context to mission.control

Cluster is starting.  It should be ready in a few minutes.

Suggestions:
 * validate cluster: kops validate cluster
 * list nodes: kubectl get nodes --show-labels
 * ssh to the master: ssh -i ~/.ssh/id_rsa admin@api.mission.control
 * the admin user is specific to Debian. If not using Debian please use the appropriate user based on your OS.
 * read about installing addons at: https://kops.sigs.k8s.io/operations/addons.
```

### CODE REVIEW

**Comment by lazzarello** [comment]
It looks like the e2e test is repeatedly failing when trying to upload to GCP. This doesn't seem to be related to my changes.

Unrelated...I tested deletion with my build off this PR and that works as expected. So that's good.

File: pkg/model/iam/iam_builder.go [hunk 1]
```diff
@@ -536,10 +536,12 @@ func addECRPermissions(p *Policy) {
 	})
 }
 
-func addRoute53Permissions(p *Policy, hostedZoneID string) {
+func (b *PolicyBuilder) addRoute53Permissions(p *Policy, hostedZoneID string) {
 
 	// TODO: Route53 currently not supported in China, need to check and fail/return
-
+	//if b.IAMPrefix() == "arn:aws-cn" {
```
Comment (rifelpet) [inline pkg/model/iam/iam_builder.go]: we can probably remove this commented code right?

Comment (lazzarello) [reply pkg/model/iam/iam_builder.go]: yeah. I was a little more ambitious when I started but realized I probably shouldn't be adding two things when I only want to fix one bug  :)

Comment (johngmyers) [reply pkg/model/iam/iam_builder.go]: Ah, I read this as adding a suggestion to the TODO.
