### PR TITLE
Validation: don't expect bastion nodes to join

### LINKED ISSUE #4761: Cluster validation fails if using a bastion
Kops Version 1.9.0-alpha.2 (git-d21a065f7)

`kops validate cluster` fails with a message like:

```
VALIDATION ERRORS
KIND	NAME			MESSAGE
Machine	i-0c38d7f9ec6b02c77	machine "i-0c38d7f9ec6b02c77" has not yet joined cluster
```

If using a bastion, it apparently is expected to show up in the node list but never will...

### PR DESCRIPTION
**Pull request by justinsb**
Fix #4761

### CODE REVIEW

File: pkg/validation/validate_cluster.go [hunk 1]
```diff
@@ -219,11 +219,19 @@ func (v *ValidationCluster) validateNodes(cloudGroups map[string]*cloudinstances
...
-					Name:    member.ID,
-					Message: fmt.Sprintf("machine %q has not yet joined cluster", member.ID),
-				})
+				nodeExpectedToJoin := true
+				if cloudGroup.InstanceGroup.Spec.Role == kops.InstanceGroupRoleBastion {
+					// bastion nodes don't join the cluster
+					nodeExpectedToJoin = false
+				}
+
+				if nodeExpectedToJoin {
```
Comment (chrislovecnm) [inline pkg/validation/validate_cluster.go]: Why don't we have?

```go
if cloudGroup.InstanceGroup.Spec.Role != kops.InstanceGroupRoleBastion {
  v.addError(&ValidationError{
						Kind:    "Machine",
						Name:    member.ID,
						Message: fmt.Sprintf("machine %q has not yet joined cluster", member.ID),
					})
}
```

Confused why we have an extra if ...

Comment (justinsb) [reply pkg/validation/validate_cluster.go]: Because we expect more roles in future, and I find this code to be more self-descriptive (at the expense of being longer, admittedly)

Comment (chrislovecnm) [reply pkg/validation/validate_cluster.go]: yes more flexiable ... k
