### PR TITLE
fix hostnames in kops openstack

### LINKED ISSUE #6441: hostname is not defined correctly in machines
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

master

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.11.6

**3. What cloud provider are you using?**
openstack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops create cluster \
  --cloud openstack \
  --name oma.k8s.local \
  --state ${KOPS_STATE_STORE} \
  --zones nova \
  --network-cidr 10.1.0.0/16 \
  --image ubuntu \
  --master-count=3 \
  --node-count=1 \
  --node-size m1.small \
  --master-size m1.small \
  --etcd-storage-type lvmdriver-1 \
  --api-loadbalancer-type public \
  --topology private \
  --bastion \
  --networking weave \
  --os-ext-net public --yes
```

**5. What happened after the commands executed?**

After cluster is up and running, each instance hostname is same called `oma`. 

**6. What did you expect to happen?**

I except that each instance should have its own exact same hostname that exist in cloudprovider api (in this case openstack). Example: `oma.k8s.local-master-nova-1-1` or `oma.k8s.local-master-nova-2-1` and so on. Should we insert this to cloud-init? 

/kind bug

### PR DESCRIPTION
**Pull request by zetaab**
fixes #6441 

```
% openstack server list
+--------------------------------------+-------------------------------+--------+-----------------------------------------+--------+----------+
| ID                                   | Name                          | Status | Networks                                | Image  | Flavor   |
+--------------------------------------+-------------------------------+--------+-----------------------------------------+--------+----------+
| 83df9825-22cd-49c0-8f0e-ff90a7372832 | bastions-1.oma.k8s.local      | ACTIVE | oma.k8s.local=10.1.1.196, 192.168.1.206 | ubuntu | ds1G     |
| a83c3663-a07e-4cca-a8d2-53e4905d1259 | nodes-1.oma.k8s.local         | ACTIVE | oma.k8s.local=10.1.1.156                | ubuntu | m1.small |
| e3845789-1c6c-40ac-bd51-dbfd29df9051 | master-nova-2-1.oma.k8s.local | ACTIVE | oma.k8s.local=10.1.2.218                | ubuntu | m1.small |
| 0ca71cd0-b0fb-41fc-8628-296f3007e5b8 | master-nova-1-1.oma.k8s.local | ACTIVE | oma.k8s.local=10.1.1.12                 | ubuntu | m1.small |
| d4fed7f6-21aa-484a-8e1b-733eadb14060 | master-nova-3-1.oma.k8s.local | ACTIVE | oma.k8s.local=10.1.1.225                | ubuntu | m1.small |
+--------------------------------------+-------------------------------+--------+-----------------------------------------+--------+----------+
```

Kubernetes: (these will be fixed if openstack cloudprovider will start parsing hostnames correctly)
```
% kubectl get nodes
NAME                            STATUS     ROLES     AGE       VERSION
master-nova-1-1.oma.k8s.local   Ready      master    48s       v1.11.6
master-nova-2-1.oma.k8s.local   Ready      master    27s       v1.11.6
master-nova-3-1.oma.k8s.local   Ready      master    45s       v1.11.6
nodes-1.oma.k8s.local           NotReady   node      2s        v1.11.6
```

and hostnames are now in machines like `bastions-1`, `nodes-1`, `master-nova-2-1` and so on.

### CODE REVIEW

**Comment by zetaab** [comment]
/hold 

Waiting for https://github.com/kubernetes/cloud-provider-openstack/pull/467

Also I am thinking that could we just replace `.` with `-` in hostname.

Then the hostnames in linux should work, and in openstack also. Example: `master-nova-1-1.oma.k8s.local` -> `master-nova-1-1-oma-k8s-local`

@chrisz100 what you think? Then that PR to upstream openstack is not needed if we just replace dots

**Comment by drekle** [comment]
Been testing with a variety of helm charts.  There are a number which have podAntiAffinity rules which require this PR to work correctly.

**Comment by zetaab** [comment]
and this PR is must if we want to get external CCM working. (I am working with that in another PR)

**Comment by zetaab** [comment]
@dims could you approve if ok?

File: pkg/resources/openstack/instances.go [hunk 1]
```diff
@@ -29,32 +29,31 @@ const (
...
-		resourceTrackers = append(resourceTrackers, floatingIPs...)
-
-		resourceTracker := &resources.Resource{
-			Name: instance.Name,
-			ID:   instance.ID,
-			Type: typeInstance,
-			Deleter: func(cloud fi.Cloud, r *resources.Resource) error {
-				return cloud.(openstack.OpenstackCloud).DeleteInstanceWithID(r.ID)
-			},
+		val, ok := instance.Metadata["k8s"]
```
Comment (justinsb) [inline pkg/resources/openstack/instances.go]: FYI on AWS we use `kubernetes.io/cluster/<cluster-name>=shared` and `kubernetes.io/cluster/<cluster-name>=owned`.  `<cluster-name>` can be anything but for kops we use the name of the cluster you create.

We originally had `KubernetesCluster=<cluster-name>` but this made it hard to have shared resources.

Comment (justinsb) [reply pkg/resources/openstack/instances.go]: (and it looks like GCP is using `kubernetes.io/cluster-id=<cluster-name>`, but only in the description field for GCLBs https://github.com/kubernetes/kubernetes/blob/1c557b9ce866d67ec6088f37058e8594b89606ee/pkg/cloudprovider/providers/gce/gce_loadbalancer_external.go#L862
