### PR TITLE
Treat NatGatewaysNotFound error as already-deleted

### LINKED ISSUE #8424: Unable to recover from failed cluster deletion
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

`Version 1.15.0 (git-ecffaff)`
(this is a private fork)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.15.9

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

`kops delete cluster --name REDACTED --state REDACTED --yes`

**5. What happened after the commands executed?**

The first time, it failed with:

```
subnet:subnet-08f4c2ba4b71c9492	still has dependencies, will retry
subnet:subnet-015189c75e105f5cc	still has dependencies, will retry
subnet:subnet-0655ae5887a06b155	still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
	route-table:rtb-0c47d709931c7f1bd
	route-table:rtb-07f3c8a3d94b134c8
	subnet:subnet-08f4c2ba4b71c9492
	route-table:rtb-09b6a1f0eeb6ae5fe
	subnet:subnet-015189c75e105f5cc
	subnet:subnet-0655ae5887a06b155
subnet:subnet-0655ae5887a06b155	still has dependencies, will retry
subnet:subnet-015189c75e105f5cc	still has dependencies, will retry
subnet:subnet-08f4c2ba4b71c9492	still has dependencies, will retry
Not all resources deleted; waiting before reattempting deletion
	subnet:subnet-015189c75e105f5cc
	route-table:rtb-09b6a1f0eeb6ae5fe
	subnet:subnet-0655ae5887a06b155
	route-table:rtb-0c47d709931c7f1bd
	route-table:rtb-07f3c8a3d94b134c8
	subnet:subnet-08f4c2ba4b71c9492

not making progress deleting resources; giving up
```

The subnets couldn't be deleted due to an apparent transient AWS issue: one of the deleted ELBs was still holding IPs from those subnets. After a weekend, the subnets could be deleted.

After deleting the subnets, reattempting a `kops delete cluster ... --yes` resulted in:

```
error from DescribeNatGateways: NatGatewayNotFound: NAT gateway nat-0a8aa3ba56bb61389 was not found
	status code: 400, request id: 9be9785e-09e2-4e71-9466-2eeb29d5790a
```

**6. What did you expect to happen?**

The second `kops delete cluster` should have continued to delete the cluster and removed the cluster from the state store.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

I believe `aws.FindNatGateways()` needs to tolerate this particular error from `c.EC2().DescribeNatGateways()`, treating it as having returned zero NAT gateways.

### PR DESCRIPTION
**Pull request by johngmyers**
Fixes #8424

### CODE REVIEW

File: pkg/resources/aws/aws.go [hunk 1]
```diff
@@ -1324,6 +1324,10 @@ func FindNatGateways(cloud fi.Cloud, routeTables map[string]*resources.Resource,
 		}
 		response, err := c.EC2().DescribeNatGateways(request)
 		if err != nil {
+			if awsup.AWSErrorCode(err) == "NatGatewayNotFound" {
+				klog.V(2).Infof("Got NatGatewayNotFound describing NatGateways; will treat as already-deleted")
```
Comment (hakman) [inline pkg/resources/aws/aws.go:1328]: I think this is or may be used in the future in some other places also. 
```suggestion
				klog.Warningf("Got NatGatewayNotFound describing NatGateways; will treat as deleted")
```

Comment (johngmyers) [reply pkg/resources/aws/aws.go:1328]: All the other "will treat as already-deleted" log lines are at `V(2).Infof`, why should this one be at `Warningf`?

Comment (hakman) [reply pkg/resources/aws/aws.go:1328]: Didn't see those other ones, sorry. Please ignore.

File: pkg/resources/aws/aws.go [hunk 2]
```diff
@@ -1324,6 +1324,10 @@ func FindNatGateways(cloud fi.Cloud, routeTables map[string]*resources.Resource,
 		}
 		response, err := c.EC2().DescribeNatGateways(request)
 		if err != nil {
+			if awsup.AWSErrorCode(err) == "NatGatewayNotFound" {
```
Comment (rifelpet) [inline pkg/resources/aws/aws.go:1327]: If we pass in multiple nat gateway IDs, this will assume that all of them are already deleted, correct? Perhaps we should break this out into separate DescribeNatGateway calls per natGatewayId? I worry that we could leave orphaned NAT Gateways lying around which cost ~$30 USD/month. The old behavior made this situation more visible to the user since the kops command would fail, but now a user may not notice this situation.

Comment (johngmyers) [reply pkg/resources/aws/aws.go:1327]: I'll run a test.

Comment (johngmyers) [reply pkg/resources/aws/aws.go:1326]: It never occurred to me that the API could behave that badly. Rewritten.
