### PR TITLE
Skip deletion processing for terraform

### LINKED ISSUE #1515: Creating an IG in a cluster with a modified VPC causes errors (terraform)
To reproduce:

```
kops create cluster --cloud=aws \
                    --zones=ca-central-1a,ca-central-1b \
                    --node-size m4.xlarge \
                    --master-size m4.large \
                    --vpc vpc-xxx \
                    --network-cidr=10.240.0.0/16 \
                    --channel alpha \
                    --kubernetes-version 1.5.2 \
                    --bastion \
                    --topology private \
                    --networking calico \
                    --name "${CLUSTER_URL}"

kops update cluster "${CLUSTER_URL}" --target=terraform
```

Then, I modified the outputted terraform by adding a `aws_vpc`, replacing the `vpc-xxx` references in the terraform with the new vpc. I also added an elb, security group for the elb, and some extra rules for the nodes security group allowing traffic from that elb.

After applying the terraform, I edited the cluster via `kops edit`, and updated the VPC. Then, I tried to create a new IG. After closing the editor of the IG, the below errors occur:

```
W0117 16:00:11.565278   10634 securitygrouprule.go:155] SourceGroup had nil ID: *awstasks.SecurityGroup {"Name":"bastion.cluster","ID":null,"Description":"Security group for bastion","VPC":{"Name":"cluster","ID":"vpc-ca1ee2a3","CIDR":"10.240.0.0/16","EnableDNSHostnames":true,"EnableDNSSupport":true,"Shared":true},"RemoveExtraRules":["port=22"]}
W0117 16:00:11.565360   10634 securitygrouprule.go:155] SourceGroup had nil ID: *awstasks.SecurityGroup {"Name":"bastion-elb.cluster","ID":null,"Description":"Security group for bastion ELB","VPC":{"Name":"cluster","ID":"vpc-ca1ee2a3","CIDR":"10.240.0.0/16","EnableDNSHostnames":true,"EnableDNSSupport":true,"Shared":true},"RemoveExtraRules":["port=22"]}
W0117 16:00:11.590457   10634 securitygrouprule.go:155] SourceGroup had nil ID: *awstasks.SecurityGroup {"Name":"bastion.cluster","ID":null,"Description":"Security group for bastion","VPC":{"Name":"cluster","ID":"vpc-ca1ee2a3","CIDR":"10.240.0.0/16","EnableDNSHostnames":true,"EnableDNSSupport":true,"Shared":true},"RemoveExtraRules":["port=22"]}
W0117 16:00:11.590539   10634 securitygrouprule.go:155] SourceGroup had nil ID: *awstasks.SecurityGroup {"Name":"bastion-elb.cluster","ID":null,"Description":"Security group for bastion ELB","VPC":{"Name":"cluster","ID":"vpc-ca1ee2a3","CIDR":"10.240.0.0/16","EnableDNSHostnames":true,"EnableDNSSupport":true,"Shared":true},"RemoveExtraRules":["port=22"]}
W0117 16:00:11.590584   10634 securitygrouprule.go:155] SourceGroup had nil ID: *awstasks.SecurityGroup {"Name":"bastion.cluster","ID":null,"Description":"Security group for bastion","VPC":{"Name":"cluster","ID":"vpc-ca1ee2a3","CIDR":"10.240.0.0/16","EnableDNSHostnames":true,"EnableDNSSupport":true,"Shared":true},"RemoveExtraRules":["port=22"]}
W0117 16:00:11.590631   10634 securitygrouprule.go:155] SourceGroup had nil ID: *awstasks.SecurityGroup {"Name":"nodes.cluster","ID":null,"Description":"Security group for nodes","VPC":{"Name":"cluster","ID":"vpc-ca1ee2a3","CIDR":"10.240.0.0/16","EnableDNSHostnames":true,"EnableDNSSupport":true,"Shared":true},"RemoveExtraRules":["port=22"]}
W0117 16:00:11.590678   10634 securitygrouprule.go:155] SourceGroup had nil ID: *awstasks.SecurityGroup {"Name":"api-elb.cluster","ID":null,"Description":"Security group for api ELB","VPC":{"Name":"cluster","ID":"vpc-ca1ee2a3","CIDR":"10.240.0.0/16","EnableDNSHostnames":true,"EnableDNSSupport":true,"Shared":true},"RemoveExtraRules":["port=443"]}
W0117 16:00:11.590724   10634 securitygrouprule.go:155] SourceGroup had nil ID: *awstasks.SecurityGroup {"Name":"nodes.cluster","ID":null,"Description":"Security group for nodes","VPC":{"Name":"cluster","ID":"vpc-ca1ee2a3","CIDR":"10.240.0.0/16","EnableDNSHostnames":true,"EnableDNSSupport":true,"Shared":true},"RemoveExtraRules":["port=22"]}
W0117 16:00:11.590763   10634 securitygrouprule.go:155] SourceGroup had nil ID: *awstasks.SecurityGroup {"Name":"nodes.cluster","ID":null,"Description":"Security group for nodes","VPC":{"Name":"cluster","ID":"vpc-ca1ee2a3","CIDR":"10.240.0.0/16","EnableDNSHostnames":true,"EnableDNSSupport":true,"Shared":true},"RemoveExtraRules":["port=22"]}
W0117 16:00:11.590802   10634 securitygrouprule.go:155] SourceGroup had nil ID: *awstasks.SecurityGroup {"Name":"api-elb.cluster","ID":null,"Description":"Security group for api ELB","VPC":{"Name":"cluster","ID":"vpc-ca1ee2a3","CIDR":"10.240.0.0/16","EnableDNSHostnames":true,"EnableDNSSupport":true,"Shared":true},"RemoveExtraRules":["port=443"]}
W0117 16:00:11.590843   10634 securitygrouprule.go:155] SourceGroup had nil ID: *awstasks.SecurityGroup {"Name":"nodes.cluster","ID":null,"Description":"Security group for nodes","VPC":{"Name":"cluster","ID":"vpc-ca1ee2a3","CIDR":"10.240.0.0/16","EnableDNSHostnames":true,"EnableDNSSupport":true,"Shared":true},"RemoveExtraRules":["port=22"]}
...
W0117 16:00:11.590943   10634 executor.go:109] error running task "SecurityGroup/bastion.cluster" (8m57s remaining to succeed): unexpected target type for deletion: *terraform.TerraformTarget
W0117 16:00:11.590985   10634 executor.go:109] error running task "SecurityGroup/nodes.cluster" (8m57s remaining to succeed): unexpected target type for deletion: *terraform.TerraformTarget
W0117 16:00:11.591015   10634 executor.go:109] error running task "SecurityGroup/masters.cluster" (8m57s remaining to succeed): unexpected target type for deletion: *terraform.TerraformTarget
```
@justinsb

### PR DESCRIPTION
**Pull request by justinsb**
Terraform processes deletions itself

Fix #1515

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1572)

### CODE REVIEW

File: federation/targets/kubernetes/kubernetestarget.go [hunk 1]
```diff
@@ -69,6 +69,11 @@ func (t *KubernetesTarget) Finish(taskMap map[string]fi.Task) error {
 	return nil
 }
 
+func (t *KubernetesTarget) ProcessDeletions() bool {
+	// We don't expect any, but it would be up to us to process
+	return true
```
Comment (kris-nova) [inline federation/targets/kubernetes/kubernetestarget.go]: Seems odd... but if you say so!
