### PR TITLE
Remove cloud-config and cloud-provider from 1.33 apiserver

### LINKED ISSUE #17267: Kubernetes 1.33 does not accept --cloud-config
/kind bug

kOps CI testing Kubernetes master is red since 2025-02-17, https://testgrid.k8s.io/kops-latest#kops-aws-amd64-conformance

`kube-apiserver --cloud-config` and `--cloud-provider` have been deprecated for quite some time, now they're removed for real and the newest API server won't come up.

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

v1.32.0-beta.1-20-g99ba10e2d5 (current [latest-ci-updown-green.txt](https://storage.googleapis.com/k8s-staging-kops/kops/releases/markers/master/latest-ci-updown-green.txt))

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

Latest master,  https://storage.googleapis.com/k8s-release-dev/ci/v1.33.0-alpha.2.28+7fc8a86381d874

**3. What cloud provider are you using?**
AWS

**4.  What is the simplest way to reproduce this issue?**
See CI e.g. https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/e2e-kops-aws-amd64-conformance/1892186901553614848

**5. What happened after the commands executed?**
The API server fails with `Error: unknown flag: --cloud-config`

**6. What did you expect to happen?**
Green CI :-)

### PR DESCRIPTION
**Pull request by rifelpet**
Fixes #17267

### CODE REVIEW

File: pkg/model/components/apiserver.go [hunk 1]
```diff
@@ -97,29 +97,31 @@ func (b *KubeAPIServerOptionsBuilder) BuildOptions(cluster *kops.Cluster) error
...
+			c.CloudProvider = "openstack"
+		case kops.CloudProviderAzure:
+			c.CloudProvider = "azure"
+		case kops.CloudProviderScaleway:
+			c.CloudProvider = "external"
+		case kops.CloudProviderMetal:
+			c.CloudProvider = "external"
+		default:
+			return fmt.Errorf("unknown cloudprovider %q", cluster.GetCloudProvider())
+		}
```
Comment (elmiko) [inline pkg/model/components/apiserver.go:120]: i'm not sure how this `c.CloudProvider` value is used, but we do not allow any value other than `external` for the `--cloud-provider` flag.

File: pkg/apis/kops/validation/legacy.go [hunk 2]
```diff
@@ -182,8 +187,10 @@ func ValidateCluster(c *kops.Cluster, strict bool, vfsContext *vfs.VFSContext) f
 				}
 			}
 			if c.Spec.KubeAPIServer != nil && (strict || c.Spec.KubeAPIServer.CloudProvider != "") {
-				if c.Spec.KubeAPIServer.CloudProvider != "external" && k8sCloudProvider != c.Spec.KubeAPIServer.CloudProvider {
-					allErrs = append(allErrs, field.Forbidden(fieldSpec.Child("kubeAPIServer", "cloudProvider"), "Did not match cluster cloudProvider"))
+				if k8sVersion != nil && k8sVersion.LT(semver.MustParse("1.33.0")) {
+					if c.Spec.KubeAPIServer.CloudProvider != "external" && k8sCloudProvider != c.Spec.KubeAPIServer.CloudProvider {
```
Comment (stlaz) [inline pkg/apis/kops/validation/legacy.go:191]: isn't this flag gone from KAS completely, meaning even `external` would be invalid? Isn't that the value allowed in kubelet, rather than KAS?

**Review by hakman — APPROVED** [review]
