### PR TITLE
Make aws-cni config more flexible and generalized

### LINKED ISSUE #11144: AWS_VPC_K8S_CNI_RANDOMIZESNAT environment variable for `spec.networking.amazonvpc` resets to `prng` on every upgrade
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.19.1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.18.12

**3. What cloud provider are you using?**

aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

In `cluster.yaml`

```
spec:
  networking:
    amazonvpc:
      env:
        - name: AWS_VPC_K8S_CNI_EXTERNALSNAT
          value: "false"
        - name: AWS_VPC_K8S_CNI_RANDOMIZESNAT
          value: none
        - name: MAX_ENI
          value: none
        - name: WARM_IP_TARGET
          value: "2"
```

`kops update cluster && kops rolling-update cluster`

**5. What happened after the commands executed?**

From `kubectl get ds -n kube-system aws-node -oyaml`

```
spec:
  template:
    spec:
      containers:
      - env:
        - name: ADDITIONAL_ENI_TAGS
          value: '{}'
        - name: AWS_VPC_CNI_NODE_PORT_SUPPORT
          value: "true"
        - name: AWS_VPC_ENI_MTU
          value: "9001"
        - name: AWS_VPC_K8S_CNI_CONFIGURE_RPFILTER
          value: "false"
        - name: AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG
          value: "false"
        - name: AWS_VPC_K8S_CNI_EXTERNALSNAT
          value: "prng"
        - name: AWS_VPC_K8S_CNI_LOGLEVEL
          value: DEBUG
        - name: AWS_VPC_K8S_CNI_LOG_FILE
          value: /host/var/log/aws-routed-eni/ipamd.log
        - name: AWS_VPC_K8S_CNI_RANDOMIZESNAT
          value: none
        - name: AWS_VPC_K8S_CNI_VETHPREFIX
          value: eni
        - name: AWS_VPC_K8S_PLUGIN_LOG_FILE
          value: /var/log/aws-routed-eni/plugin.log
        - name: AWS_VPC_K8S_PLUGIN_LOG_LEVEL
          value: DEBUG
        - name: DISABLE_INTROSPECTION
          value: "false"
        - name: DISABLE_METRICS
          value: "false"
        - name: ENABLE_POD_ENI
          value: "false"
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: WARM_ENI_TARGET
          value: "1"
        - name: CLUSTER_NAME
          value: [REDACTED]
        - name: MAX_ENI
          value: "1"
        - name: WARM_IP_TARGET
          value: "1"
```

**6. What did you expect to happen?**

`AWS_VPC_K8S_CNI_EXTERNALSNAT` should be set to `none`

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2018-10-31T22:42:45Z"
  name: [REDACTED]
spec:
  additionalPolicies:
    node: |
      [
        [REDACTED]
      ]
  api:
    loadBalancer:
      class: Classic
      type: Private
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    environment: [REDACTED]
  cloudProvider: aws
  configBase: s3://[REDACTED]
  dnsZone: [REDACTED]
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
      volumeType: gp3
    - instanceGroup: master-us-east-1b
      name: b
      volumeType: gp3
    - instanceGroup: master-us-east-1c
      name: c
      volumeType: gp3
    name: main
  - etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
      volumeType: gp3
    - instanceGroup: master-us-east-1b
      name: b
      volumeType: gp3
    - instanceGroup: master-us-east-1c
      name: c
      volumeType: gp3
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeControllerManager:
    horizontalPodAutoscalerDownscaleStabilization: 22m0s
  kubeDNS:
    provider: CoreDNS
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.18.12
  masterInternalName: api.internal.[REDACTED]
  masterPublicName: api.[REDACTED]
  networkCIDR: 10.3.0.0/16
  networking:
    amazonvpc:
      env:
      - name: AWS_VPC_K8S_CNI_EXTERNALSNAT
        value: "false"
      - name: AWS_VPC_K8S_CNI_RANDOMIZESNAT
        value: none
      - name: MAX_ENI
        value: "1"
      - name: WARM_IP_TARGET
        value: "1"
      imageName: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.6.3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets: [REDACTED]
  topology:
    bastion:
      bastionPublicName: bastion.[REDACTED]
    dns:
      type: Public
    masters: private
    nodes: private
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
`AWS_VPC_K8S_CNI_RANDOMIZESNAT` continues to reset to `"prng"` on every upgrade

### PR DESCRIPTION
**Pull request by MoShitrit**
Fixes #11144 
/cc @hakman

### CODE REVIEW

File: pkg/apis/kops/networking.go [hunk 1]
```diff
@@ -248,12 +248,19 @@ type RomanaNetworkingSpec struct {
 
 // AmazonVPCNetworkingSpec declares that we want Amazon VPC CNI networking
 type AmazonVPCNetworkingSpec struct {
+	// Specifies whether ipamd should configure rp filter for primary interface.
+	// Setting this to false will require rp filter to be configured through init container.
+	AwsVpcK8sCniConfigureRpFilter string   `json:"awsVpcK8sCniConfigureRpFilter,omitempty"`
+	Env                           []EnvVar `json:"env,omitempty"`
```
Comment (johngmyers) [inline pkg/apis/kops/networking.go:254]: Should not remove the documentation comment

File: pkg/apis/kops/networking.go [hunk 2]
```diff
@@ -248,12 +248,19 @@ type RomanaNetworkingSpec struct {
 
 // AmazonVPCNetworkingSpec declares that we want Amazon VPC CNI networking
 type AmazonVPCNetworkingSpec struct {
+	// Specifies whether ipamd should configure rp filter for primary interface.
```
Comment (johngmyers) [inline pkg/apis/kops/networking.go:251]: Doc comment needs to start with the name of the field.

File: pkg/apis/kops/networking.go [hunk 3]
```diff
@@ -248,12 +248,19 @@ type RomanaNetworkingSpec struct {
...
+	// Setting this to false will require rp filter to be configured through init container.
+	AwsVpcK8sCniConfigureRpFilter string   `json:"awsVpcK8sCniConfigureRpFilter,omitempty"`
+	Env                           []EnvVar `json:"env,omitempty"`
+	// If ENABLE_POD_ENI is set to true, in order for the kubelet to connect via TCP (for liveness or readiness probes) to pods that are using per pod security groups,
```
Comment (johngmyers) [inline pkg/apis/kops/networking.go:255]: Doc comment needs to start with the name of the field.

File: upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template [hunk 4]
```diff
@@ -106,42 +106,35 @@
...
+        # - "name": "DISABLE_METRICS"
+        #   "value": "false"
+        # - "name": "ENABLE_POD_ENI"
+        #   "value": "false"
         - "name": "MY_NODE_NAME"
           "valueFrom":
             "fieldRef":
               "fieldPath": "spec.nodeName"
-        - "name": "WARM_ENI_TARGET"
-          "value": "1"
```
Comment (johngmyers) [inline upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template:144]: Did we want to comment this one out as well?

**Review by johngmyers — CHANGES_REQUESTED** [review]

**Comment by MoShitrit** [comment]
Thanks for the review, @johngmyers !
I've addressed all your comments, please have a look when you get a chance and let me know if you had any other concerns 😄 🙏🏻

File: pkg/apis/kops/networking.go [hunk 5]
```diff
@@ -248,12 +248,20 @@ type RomanaNetworkingSpec struct {
 
 // AmazonVPCNetworkingSpec declares that we want Amazon VPC CNI networking
 type AmazonVPCNetworkingSpec struct {
-	// The container image name to use
-	ImageName string `json:"imageName,omitempty"`
-	// The init container image name to use
-	InitImageName string `json:"initImageName,omitempty"`
+	// AwsVpcK8sCniConfigureRpFilter specifies whether ipamd should configure rp filter for primary interface.
+	// Setting this to false will require rp filter to be configured through init container.
+	AwsVpcK8sCniConfigureRpFilter string `json:"awsVpcK8sCniConfigureRpFilter,omitempty"`
```
Comment (johngmyers) [inline pkg/apis/kops/networking.go:253]: All of this refers to the AWS VPC CNI, so that part of the name is redundant.

"RP" is an acronym for "Reverse Path".

The possible values are "true" and "false", so it's a boolean.

```suggestion
	ConfigureRPFilter *bool `json:"configureRPFilter,omitempty"`
```

File: pkg/apis/kops/networking.go [hunk 6]
```diff
@@ -248,12 +248,20 @@ type RomanaNetworkingSpec struct {
 
 // AmazonVPCNetworkingSpec declares that we want Amazon VPC CNI networking
 type AmazonVPCNetworkingSpec struct {
-	// The container image name to use
-	ImageName string `json:"imageName,omitempty"`
-	// The init container image name to use
-	InitImageName string `json:"initImageName,omitempty"`
+	// AwsVpcK8sCniConfigureRpFilter specifies whether ipamd should configure rp filter for primary interface.
+	// Setting this to false will require rp filter to be configured through init container.
```
Comment (johngmyers) [inline pkg/apis/kops/networking.go:252]: Should mention the default is true.

File: pkg/apis/kops/networking.go [hunk 7]
```diff
@@ -248,12 +248,20 @@ type RomanaNetworkingSpec struct {
...
+	AwsVpcK8sCniConfigureRpFilter string `json:"awsVpcK8sCniConfigureRpFilter,omitempty"`
 	// Env is a list of environment variables to set in the container.
 	Env []EnvVar `json:"env,omitempty"`
+	// DisableTCPEarlyDemux should be set to true for amazon-k8s-cni-init container under initcontainers if ENABLE_POD_ENI is set to true,
+	// in order for the kubelet to connect via TCP (for liveness or readiness probes) to pods that are using per pod security groups.
+	// This will increase the local TCP connection latency slightly.
+	// To use this setting, a Linux kernel version of at least 4.6 is needed on the worker node.
+	DisableTCPEarlyDemux string `json:"disableTCPEarlyDemux,omitempty"`
```
Comment (johngmyers) [inline pkg/apis/kops/networking.go:260]: Also a boolean.

We try to avoid negative booleans.

```suggestion
	TCPEarlyDemux *bool `json:"enableTCPEarlyDemux,omitempty"`
```

File: pkg/apis/kops/networking.go [hunk 8]
```diff
@@ -248,12 +248,20 @@ type RomanaNetworkingSpec struct {
...
+	// ImageName is the container image name to use.
+	ImageName string `json:"imageName,omitempty"`
```
Comment (johngmyers) [inline pkg/apis/kops/networking.go:262]: Other subcomponents use `Image`

```suggestion
	Image string `json:"image,omitempty"`
```

File: pkg/apis/kops/networking.go [hunk 9]
```diff
@@ -248,12 +248,20 @@ type RomanaNetworkingSpec struct {
...
+	// InitImageName is the init container image name to use.
+	InitImageName string `json:"initImageName,omitempty"`
```
Comment (johngmyers) [inline pkg/apis/kops/networking.go:264]:
```suggestion
	InitImage string `json:"initImageName,omitempty"`
```

File: upup/pkg/fi/cloudup/template_functions.go [hunk 10]
```diff
@@ -149,6 +149,22 @@ func (tf *TemplateFunctions) AddTo(dest template.FuncMap, secretStore fi.SecretS
 		}
 	}
 
+	if cluster.Spec.Networking != nil && cluster.Spec.Networking.AmazonVPC != nil {
```
Comment (johngmyers) [inline upup/pkg/fi/cloudup/template_functions.go:152]: Use `WithDefaultBool` in the template.

**Review by johngmyers — CHANGES_REQUESTED** [review]

**Review by hakman — CHANGES_REQUESTED** [review]
I still think that initializing the Env vars with the options kOps overrides by default in template functions is better and also allows users to change those too in a generic way, without adding extra options.

**Comment by MoShitrit** [comment]
> I still think that initializing the Env vars with the options kOps overrides by default in template functions is better and also allows users to change those too in a generic way, without adding extra options.

So I did that with everything else, however it seems like these two are actually different from the default values according to the docs, so I needed to make an override on them. Is there a better way to handle that, than the one I used?

File: upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template (hunk 4 above)
Comment (MoShitrit) [reply upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template:144]: Done 👍🏻 
Good catch, thanks!

File: pkg/apis/kops/networking.go (hunk 8 above)
Comment (MoShitrit) [reply pkg/apis/kops/networking.go]: Yep, I didn't add that, simply moved it. 
Do we not order these parameters in an alphabetical fashion? 
And should I revert the rename back to `ImageName` and `InitImageName`?

File: upup/pkg/fi/cloudup/template_functions.go (hunk 10 above)
Comment (MoShitrit) [reply upup/pkg/fi/cloudup/template_functions.go]: Removed the template functions and switched to use `WithDefaultBool` as suggested. Thanks!

File: pkg/apis/kops/networking.go (hunk 8 above)
Comment (johngmyers) [reply pkg/apis/kops/networking.go]: Yes, revert the rename. I hadn't realized it existed before.

**Comment by hakman** [comment]
Hey @MoShitrit, sorry for the delay, but was traveling for the past few days. Will take another look at this today.

**Comment by hakman** [comment]
I would add a template function like this:
```go
	if cluster.Spec.Networking != nil && cluster.Spec.Networking.AmazonVPC != nil {
		c := cluster.Spec.Networking.AmazonVPC
		dest["AmazonVpcEnvVars"] = func() map[string]string {
			envVars := map[string]string{
				"AWS_VPC_K8S_CNI_CONFIGURE_RPFILTER": "false",
			}
			for _, e := range c.Env {
				envVars[e.Name] = e.Value
			}
			return envVars
		}
	}
```
and change the template to use it instead of directly accessing the env vars:
```go
        {{- range $name, $value := AmazonVpcEnvVars }}
        - "name": "{{ $name }}"
          "value": "{{ $value }}"
        {{- end }}
```
This way we can change the defaults, but still allow overwriting them.

File: upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template [hunk 11]
```diff
@@ -106,48 +106,44 @@
...
+        # - "name": "DISABLE_INTROSPECTION"
+        #   "value": "false"
+        # - "name": "DISABLE_METRICS"
+        #   "value": "false"
+        # - "name": "ENABLE_POD_ENI"
+        #   "value": "false"
         - "name": "MY_NODE_NAME"
           "valueFrom":
             "fieldRef":
               "fieldPath": "spec.nodeName"
```
Comment (hakman) [inline upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template:142]: Please comment this too to have a single block of comments and add it just before `CLUSTER_NAME`.

File: upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template [hunk 12]
```diff
@@ -106,48 +106,44 @@
                 - "fargate"
       "containers":
       - "env":
-        - "name": "ADDITIONAL_ENI_TAGS"
-          "value": "{}"
-        - "name": "AWS_VPC_CNI_NODE_PORT_SUPPORT"
-          "value": "true"
-        - "name": "AWS_VPC_ENI_MTU"
-          "value": "9001"
```
Comment (hakman) [inline upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template:114]: These should be added back as comments, seem to just be gone.

**Review by hakman — CHANGES_REQUESTED** [review]
These are just some remaining nits, otherwise looks good from my point of view. Maybe also squash the commits.
@rifelpet Want to take a look too?

File: upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template (hunk 11 above)
Comment (hakman) [reply upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template:154]: Seems that this was not a good idea, looks worse. Would you mind reverting this change and squash?

Comment (MoShitrit) [reply upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template:148]: Done! 😄

Comment (hakman) [reply upup/models/cloudup/resources/addons/networking.amazon-vpc-routed-eni/k8s-1.16.yaml.template:148]: Thanks!

**Comment by rifelpet** [comment]
/lgtm

Will let @hakman do the final approval

**Review by hakman — APPROVED** [review]
Thanks @MoShitrit!
