### PR TITLE
Add fixed version to all addons

### LINKED ISSUE #12249: Unable to update cluster from 1.21 -> 1.22, kops controller crashlooping in AWS
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.22 beta 1

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.22.1

**3. What cloud provider are you using?**

AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

I am updating cluster from 1.21.x k8s (it was installed by using kops 1.21) to 1.22.1 (using kops 1.22 beta 1)

**5. What happened after the commands executed?**

I see kops-controller in new 1.22.1 master crashlooping

```
kops-controller-fzdhz                                                    0/1     CrashLoopBackOff   8 (4m33s ago)   20m   10.124.44.193     ip-10-124-44-193.eu-central-1.compute.internal    <none>           <none>
```

```
% kubectl logs kops-controller-fzdhz
E0902 06:26:05.813281       1 deleg.go:144] setup "msg"="unable to start server" "error"="reading \"kubernetes-ca\" certificate: open /etc/kubernetes/kops-controller/pki/kubernetes-ca.pem: no such file or directory"
```

**6. What did you expect to happen?**
-

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

### PR DESCRIPTION
**Pull request by olemarkus**
This should ensure addon updates are triggered before rolling the cluster, as expected.
We also update addons before labeling masters to ensure that kops-controller is updated before it is scheduled.

Should hopefully fix #12249

/cc @zetaab

### CODE REVIEW

**Review by hakman — CHANGES_REQUESTED** [review]
Can you set Version as KopsVersion? Should be good enough for what we want upgraded and won't be a strange fixed number.

File: upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go [hunk 1]
```diff
@@ -105,6 +105,11 @@ func (b *BootstrapChannelBuilder) Build(c *fi.ModelBuilderContext) error {
 	}
 
 	for _, a := range addons.Spec.Addons {
+		// Older versions of channels that may be running on the upgrading cluster requires Version to be set
+		// We hardcode version to a high version to ensure an update is triggered on first run, and from then on
+		// only a hash change will trigger an addon update.
```
Comment (rifelpet) [inline upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go:110]: Consider mentioning "This can be removed when kops no longer supports k8s 1.22"

Comment (olemarkus) [reply upup/pkg/fi/cloudup/bootstrapchannelbuilder/bootstrapchannelbuilder.go:110]: Unfortunately this follows kops versioning and we don't have any skew/upgrade jump policy. This will have to remain forever unless we change this

**Comment by olemarkus** [comment]
> Can you set Version as KopsVersion? Should be good enough for what we want upgraded and won't be a strange fixed number.

We need to set a version that is at least as high as the old addon versions. That is 4.0.0, I think. If we don't none of these addons will be updated.

**Comment by hakman** [comment]
> > Can you set Version as KopsVersion? Should be good enough for what we want upgraded and won't be a strange fixed number.
> 
> We need to set a version that is at least as high as the old addon versions. That is 4.0.0, I think. If we don't none of these addons will be updated.

My understanding is that they will be updated once new control-plane nodes are started, we just need the kOps ones (like kops-controller) to be updated before that.

**Review by rifelpet — APPROVED** [review]
