### PR TITLE
kube-proxy: set hostname-override on AWS

### LINKED ISSUE #2915: kube-proxy needs node-name
Gives error `Failed to retrieve node info: nodes "ip-172-20-78-251" not found`

```
I0612 22:44:56.299494       5 iptables.go:175] Could not connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
I0612 22:44:56.299568       5 server.go:173] setting OOM scores is unsupported in this build
I0612 22:44:56.331025       5 server.go:225] Using iptables Proxier.
W0612 22:44:56.434212       5 server.go:469] Failed to retrieve node info: nodes "ip-172-20-78-251" not found
W0612 22:44:56.434327       5 proxier.go:293] invalid nodeIP, initializing kube-proxy with 127.0.0.1 as nodeIP
I0612 22:44:56.434353       5 server.go:249] Tearing down userspace rules.
```

### PR DESCRIPTION
**Pull request by justinsb**
So that it matches the Node.Name

Fix #2915

### CODE REVIEW

File: upup/pkg/fi/nodeup/command.go [hunk 1]
```diff
@@ -313,6 +313,13 @@ func evaluateSpec(c *api.Cluster) error {
 		return err
 	}
 
+	if c.Spec.KubeProxy != nil {
```
Comment (chrislovecnm) [inline upup/pkg/fi/nodeup/command.go]: Is this even reachable?  Nit pick that does not need to be handled in the PR.  Up to you.  Will let you self merge

**Comment by chrislovecnm** [comment]
/assign
/lgtm

Had a question that does not need to be done on this PR, but just curious.

File: upup/pkg/fi/nodeup/command.go (hunk 1 above)
Comment (justinsb) [inline upup/pkg/fi/nodeup/command.go]: Just safer
