### PR TITLE
Fix rootVolumeType accepts all volume types

### LINKED ISSUE #4256: rootVolumeType accepts only gp2 or io1
Instance group spec `rootVolumeType` seems to accept only `gp2` or `io1` type.
https://github.com/kubernetes/kops/blob/2f3f0548c25e5b6b572bf58f9945f337beb16dd4/pkg/model/awsmodel/autoscalinggroup.go#L71-L72

A SSD volume is best for production but sometimes cheaper `standard` is convenient for experimental use.
Is there any reason to limit the volume type?

I think it is nice to support following volume types as well:
- `standard`
- ~~`st1`~~
- ~~`sc1`~~

Thanks.

### PR DESCRIPTION
**Pull request by int128**
This allows `rootVolumeType` of the instance group spec accepts all volume types supported by AWS. `standard` is cheaper and good for testing. Fixes #4256.

### CODE REVIEW

**Comment by mikesplain** [comment]
Thanks so much for the PR and signing the CLA!  Looks like this could be useful, I'll take a look! Have you tested this?

/assign
/ok-to-test

File: pkg/model/awsmodel/autoscalinggroup.go [hunk 1]
```diff
@@ -60,18 +60,17 @@ func (b *AutoscalingGroupModelBuilder) Build(c *fi.ModelBuilderContext) error {
...
-				}
-			default:
+			volumeType := fi.StringValue(ig.Spec.RootVolumeType)
+			if volumeType == "" {
 				volumeType = DefaultVolumeType
 			}
 
+			volumeIops := fi.Int32Value(ig.Spec.RootVolumeIops)
+			if volumeIops == 0 {
+				volumeIops = DefaultVolumeIops
```
Comment (mikesplain) [inline pkg/model/awsmodel/autoscalinggroup.go]: Is the `DefaultVolumeIOps` okay for the other Volume types? I imagine it's fine between gp2 and io1 but should this be different for standard?

**Comment by int128** [comment]
I have tested this with following YAML of the instance group:

```
spec:
  image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2017-12-02
  machineType: m3.medium
  maxPrice: "0.02"
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 20
  rootVolumeType: standard
  subnets:
  - us-west-2a
```

and it works fine.

image

File: pkg/model/awsmodel/autoscalinggroup.go (hunk 1 above)
Comment (int128) [reply pkg/model/awsmodel/autoscalinggroup.go]: The actual `RootVolumeIops` of the launch configuration is set only if the `volumeType` is `io1`. Please see line 90.

https://github.com/int128/kops/blob/d97e0e6205ec9f1d0d79d84afc943cf8774ab71d/pkg/model/awsmodel/autoscalinggroup.go#L90-L92

**Comment by mikesplain** [comment]
Great, thanks for the contribution @int128!

/lgtm
