### PR TITLE
Disable locksmithd on CoreOS if UpdatePolicy set

### LINKED ISSUE #4458: Default setting for CoreOS automatic updates should be off
Without turning off automatic updates, instances within the cluster - masters and nodes - update and reboot themselves at random and over multiple days. This can cause service outages.

I think that automatic updates for CoreOS should be opt-in rather than the current process which is opt-out by declaring a hook during the cluster deployment process.

Tagging @gambol99 / @KashifSaadat 

1. `kops version`
```
Version 1.8.0
```

2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-09T21:51:54Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.8", GitCommit:"bc6162cc70b4a39a7f39391564e0dd0be60b39e9", GitTreeState:"clean", BuildDate:"2017-10-05T06:35:40Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

3. What cloud provider are you using?
```
AWS
```

4. What commands did you run?  What is the simplest way to reproduce this issue?
Exec into the running pods of the test application and run curl in a loop - 
```
$ systemctl status update-engine.service
```

5. What happened after the commands executed?
- You will see that update-engine is enabled for all masters and nodes.

6. What did you expect to happen?
- Automatic updates should be turned off by default so instances don't update themselves and reboot at random
- If they are to be left on by default, the update process should have a process similar to kops rolling-update

7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -oyaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.
```
NA
```

8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.
```
NA
```

9. Anything else do we need to know?
Related - 
https://github.com/kubernetes/kops/pull/3063
https://github.com/kubernetes/kops/issues/3141
[Slack conversation](https://kubernetes.slack.com/archives/C3QUFP0QM/p1518992169000136)

### PR DESCRIPTION
**Pull request by KashifSaadat**
Fixes #4458

Disable `locksmithd.service` if running CoreOS, and the following is set within your kops ClusterSpec:
```
spec:
  updatePolicy: external
```

### CODE REVIEW

**Comment by KashifSaadat** [comment]
/assign @chrislovecnm @justinsb 

Wasn't sure whether you'd prefer for this to be wrapped in an API flag? I noticed the flag [UpdatePolicy](https://github.com/kubernetes/kops/blob/1.9.0-beta.2/pkg/apis/kops/cluster.go#L127), however the default value for that flag (missing) states applying upgrades automatically, so users would need to explicitly set the value to `external` if using CoreOS.

File: pkg/apis/kops/v1alpha1/zz_generated.conversion.go [hunk 1]
```diff
@@ -2125,6 +2125,7 @@ func autoConvert_v1alpha1_KubeProxyConfig_To_kops_KubeProxyConfig(in *KubeProxyC
 	out.HostnameOverride = in.HostnameOverride
 	out.Master = in.Master
 	out.Enabled = in.Enabled
+	out.ProxyMode = in.ProxyMode
```
Comment (chrislovecnm) [inline pkg/apis/kops/v1alpha1/zz_generated.conversion.go]: For some reason we are missing this ... we will need to get this into the 1.9 release as well.  I am pushing a pr.

Comment (KashifSaadat) [reply pkg/apis/kops/v1alpha1/zz_generated.conversion.go]: Ok great, cheers 👍

**Comment by KashifSaadat** [comment]
Hey @euank, many thanks for the detailed feedback! :)

Option 2 does sound like a more sensible approach in this scenario, and we could also add the ability for users to enable the CLUO deployment for their Cluster if they want it (although there's still the case that the ASG would launch an outdated AMI).

I'll make the suggested update to this PR, would also be good to hear others thoughts on CLUO and whether we should add that capability to deploy it for the user within Kops here.

Thanks!
Kash

File: nodeup/pkg/model/update_service.go [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+	return nil
+}
+
+func (b *UpdateServiceBuilder) buildCoreOSSystemdService() *nodetasks.Service {
+	manifest := &systemd.Manifest{}
+	manifest.Set("Unit", "Description", "Automatic OS Update Service disabler")
+
+	manifest.Set("Unit", "Before", "update-engine.service locksmithd.service")
+	manifest.Set("Service", "Type", "oneshot")
+	manifest.Set("Service", "ExecStartPre", "/bin/sh -c 'systemctl mask --now update-engine.service && systemctl mask --now locksmithd.service'")
```
[the remark this answers is not in the document]
Comment (KashifSaadat) [reply nodeup/pkg/model/update_service.go]: Ah yes good spot, I'll update and test

**Comment by justinsb** [comment]
We could probably do an e2e test with CoreOS running on the beta channel - I don't think anything is stopping anyone from specifying a beta or alpha AMI, but we didn't learn of this until it was too late.

I guess this is correct; I think we probably should tie it into the existing `UpdatePolicy` field on the cluster though - by default we should probably continue to update as best we can, at least until we have a more managed update process.  I'm not sure that in-place updates make sense on clouds / virtual infrastructure, but we don't currently have an operator that reflects that, and are still planning bare metal support.

@KashifSaadat would you be OK with tweaking this to key off `UpdatePolicy`?  I don't want to surprise existing users that suddenly find their clusters are not getting updates, even if the current update strategy has caused problems..

**Comment by chrislovecnm** [comment]
@euank thanks for the review btw!

**Comment by KashifSaadat** [comment]
@justinsb sure, I've just updated the PR. Users will need to specify the following within their ClusterSpec for this change to take effect (only disabling locksmithd):
```
spec:
  updatePolicy: external
```

**Comment by gambol99** [comment]
LGTM

**Comment by jpds** [comment]
This option doesn't appear to have been documented?

**Comment by davidarcher** [comment]
@jpds it's documented here although it still says that unset means no reboots:

https://github.com/kubernetes/kops/blob/master/docs/arguments.md#updatepolicy

**Comment by seh** [comment]
This patch came up in [discussion in the "kops-users" Slack channel](https://kubernetes.slack.com/archives/C3QUFP0QM/p1617140005164900).
