### PR TITLE
fix(kubelet): parse image GC args failed

### LINKED ISSUE #17463: Setting imageMaximumGCAge makes kubelet not starting
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

Tested with these two version
Client version: 1.30.1 (git-v1.30.1)
Client version: 1.30.4 (git-v1.30.4)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.30.4
1.30.12

**3. What cloud provider are you using?**

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

With `kops edit cluster` enabled the imageMaximumGCAge setting in kubelet
```yaml
spec:
  kubelet:
    imageMaximumGCAge: 24h
```
`kops update cluster --yes`
`kops rolling-update cluster --yes`

**5. What happened after the commands executed?**

The new node don't came up, and in the syslog I got this error:
```
Jun 27 09:01:00 *** kubelet[7445]: E0627 09:01:00.750235    7445 run.go:74] "command failed" err="failed to parse kubelet flag: unknown flag: --image-maximum-gc-age"
```
According to this page, that's an invalid flag:
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

**6. What did you expect to happen?**

Node came up with the imageMaximumGCAge enabled.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

### PR DESCRIPTION
**Pull request by huhouhua**
Fixes #17463

This PR fixes the imageMinimumGCAge and imageMaximumGCAge parsing failure issue. This is because these two parameters are specified using the kubelet command line, and the kubelet command line itself does not provide these two parameters, so we need to write these two parameters into the kubelet file

Changes:
1. Change the type of imageMaximumGCAge and imageMinimumGCAge to metav1.Duration
3. Returns useful error messages when parsing fails
4. Added unit tests to cover valid and invalid cases

### CODE REVIEW

File: pkg/apis/kops/componentconfig.go [hunk 1]
```diff
@@ -234,6 +228,13 @@ type KubeletConfigSpec struct {
 	// ExperimentalAllocatableIgnoreEviction enables ignoring Hard Eviction Thresholds while calculating Node Allocatable
 	ExperimentalAllocatableIgnoreEviction *bool `json:"experimentalAllocatableIgnoreEviction,omitempty" flag:"experimental-allocatable-ignore-eviction"`
 
+	// imageMinimumGCAge is the minimum age for an unused image before it is garbage collected. Default: "2m"
+	ImageMinimumGCAge *string `json:"imageMinimumGCAge,omitempty"`
```
Comment (hakman) [inline pkg/apis/kops/componentconfig.go]: Should be backwards compatible.
```suggestion
	ImageMinimumGCAge *metav1.Duration `json:"imageMinimumGCAge,omitempty"`
```

File: pkg/apis/kops/componentconfig.go [hunk 2]
```diff
@@ -234,6 +228,13 @@ type KubeletConfigSpec struct {
...
+	// imageMaximumGCAge is the maximum age an image can be unused before it is garbage collected.
+	// The default of this field is "0s", which disables this field--meaning images won't be garbage
+	// collected based on being unused for too long. Default: "0s" (disabled)
+	ImageMaximumGCAge *string `json:"imageMaximumGCAge,omitempty"`
```
Comment (hakman) [inline pkg/apis/kops/componentconfig.go]: Should be backwards compatible.
```suggestion
	ImageMaximumGCAge *Should be backwards compatible. `json:"imageMaximumGCAge,omitempty"`
```

File: pkg/apis/kops/componentconfig.go [hunk 3]
```diff
@@ -234,6 +228,13 @@ type KubeletConfigSpec struct {
 	// ExperimentalAllocatableIgnoreEviction enables ignoring Hard Eviction Thresholds while calculating Node Allocatable
 	ExperimentalAllocatableIgnoreEviction *bool `json:"experimentalAllocatableIgnoreEviction,omitempty" flag:"experimental-allocatable-ignore-eviction"`
 
+	// imageMinimumGCAge is the minimum age for an unused image before it is garbage collected. Default: "2m"
```
Comment (hakman) [inline pkg/apis/kops/componentconfig.go]: Section should be moved back to previous location (line 134).

File: nodeup/pkg/model/kubelet.go [hunk 4]
```diff
@@ -21,11 +21,13 @@ import (
 	"context"
 	"fmt"
 	"io"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
```
Comment (hakman) [inline nodeup/pkg/model/kubelet.go]: This should be moved to the next import block (line 32).

**Review by hakman — CHANGES_REQUESTED** [review]
Hi @huhouhua, thanks for your contribution. I've added a few small comments that should simplify the PR. Please let me know if you have any questions.

File: pkg/apis/kops/componentconfig.go (hunk 1 above)
Comment (huhouhua) [reply pkg/apis/kops/componentconfig.go]: @hakman This requires changes to v1alpha2 and v1alpha3 , please review my latest commit.

File: nodeup/pkg/model/kubelet.go [hunk 5]
```diff
@@ -248,6 +248,14 @@ func buildKubeletComponentConfig(kubeletConfig *kops.KubeletConfigSpec, provider
 	if kubeletConfig.ShutdownGracePeriodCriticalPods != nil {
 		componentConfig.ShutdownGracePeriodCriticalPods = *kubeletConfig.ShutdownGracePeriodCriticalPods
 	}
+	// Assign the parsed ImageMaximumGCAge duration to the kubelet file configuration
```
Comment (hakman) [inline nodeup/pkg/model/kubelet.go]: This comment is no longer needed

File: nodeup/pkg/model/kubelet.go [hunk 6]
```diff
@@ -248,6 +248,14 @@ func buildKubeletComponentConfig(kubeletConfig *kops.KubeletConfigSpec, provider
...
+	if kubeletConfig.ImageMaximumGCAge != nil {
+		componentConfig.ImageMaximumGCAge = *kubeletConfig.ImageMaximumGCAge
+	}
+	// Assign the parsed imageMinimumGCAge duration to the kubelet file configuration
```
Comment (hakman) [inline nodeup/pkg/model/kubelet.go]: This comment is no longer needed

File: nodeup/pkg/model/kubelet_test.go [hunk 7]
```diff
@@ -19,6 +19,7 @@ package model
 import (
 	"context"
 	"fmt"
+	"k8s.io/kops/pkg/flagbuilder"
```
Comment (hakman) [inline nodeup/pkg/model/kubelet_test.go]: Please move this to line 30-40.

File: pkg/apis/kops/componentconfig.go [hunk 8]
```diff
@@ -233,7 +233,6 @@ type KubeletConfigSpec struct {
 	PodPidsLimit *int64 `json:"podPidsLimit,omitempty" flag:"pod-max-pids"`
 	// ExperimentalAllocatableIgnoreEviction enables ignoring Hard Eviction Thresholds while calculating Node Allocatable
 	ExperimentalAllocatableIgnoreEviction *bool `json:"experimentalAllocatableIgnoreEviction,omitempty" flag:"experimental-allocatable-ignore-eviction"`
-
```
Comment (hakman) [inline pkg/apis/kops/componentconfig.go]: Please add back this line.

File: pkg/apis/kops/v1alpha2/componentconfig.go [hunk 9]
```diff
@@ -132,11 +132,11 @@ type KubeletConfigSpec struct {
 	// computed (such as IPSEC).
 	NetworkPluginMTU *int32 `json:"networkPluginMTU,omitempty" flag:"network-plugin-mtu"`
 	// imageMinimumGCAge is the minimum age for an unused image before it is garbage collected. Default: "2m"
-	ImageMinimumGCAge *string `json:"imageMinimumGCAge,omitempty" flag:"image-minimum-gc-age"`
+	ImageMinimumGCAge *metav1.Duration `json:"imageMinimumGCAge,omitempty"`
```
Comment (hakman) [inline pkg/apis/kops/v1alpha2/componentconfig.go:135]: Please also update `pkg/apis/kops/v1alpha3/componentconfig.go`:
https://github.com/kubernetes/kops/blob/6d1ba3dfbc3ea23094d62eeeb8559af9d04e7642/pkg/apis/kops/v1alpha3/componentconfig.go#L135-L140

**Review by hakman — CHANGES_REQUESTED** [review]

File: pkg/apis/kops/v1alpha2/componentconfig.go (hunk 9 above)
Comment (huhouhua) [reply pkg/apis/kops/v1alpha2/componentconfig.go:135]: @hakman The latest commit has been modified

**Comment by hakman** [comment]
Issue is unrelated to current fix:
/overide pull-kops-e2e-cni-amazonvpc

**Comment by hakman** [comment]
@huhouhua Thanks, this looks great.
Would you mind squashing the commits as the final step?

**Comment by huhouhua** [comment]
> @huhouhua Thanks, this looks great. Would you mind squashing the commits as the final step?

I have merged
