### PR TITLE
Only delete node object on GCE

### LINKED ISSUE #13259: Kubelet recreating node lease after node object has been deleted
During rolling upgrades the following happens:
* Drain node
* Terminate instance
* Delete node object
* Node lease object deleted as part of the cascade since the lease has the node object as owner

After deleting the node object, and the lease with it, there is a high chance that kubelet will recreate the lease object. Especially after enabling graceful shutdowns. Since the node object is gone, it will not set the ownerRef on the lease, which is causing our E2E to fail. This behavior is somewhat questionable as kubelet is aware it is being shut down, and the lease doesn't make that much sense without the node object in the first place.

Consequence is anyways that lease objects are being created and never cleaned up.

There are a couple of ways this could be solved:
* Change behavior in kubelet
* cloudup or kops-controller cleans up lease objects of terminated instances
* We stop deleting node objects, and just let CCM clean them up. In general this is not a problem as CCM will clean up nodes faster than new nodes are being provisioned. There is a comment on GCP will recycle node names, but I am not sure if we then either make an exception for GCP or if we just leave it be.

I want to do the latter. Let CCM discover instances are terminated and delete the nodes.

/kind bug
/kind office-hours

### PR DESCRIPTION
**Pull request by olemarkus**
I don't see why the GCE CCM shouldn't have deleted the node object before the new kublet registers given that the NodeLifecycle controller runs every 40 seconds ... But until we can test, we keep this for GCE.

/cc @justinsb @hakman @johngmyers 

fixes #13259

### CODE REVIEW

File: pkg/instancegroups/rollingupdate_test.go [hunk 1]
```diff
@@ -222,17 +222,14 @@ func TestRollingUpdateAllNeedUpdate(t *testing.T) {
 		case testingclient.PatchAction:
 			if string(a.GetPatch()) == cordonPatch {
 				assertCordon(t, a)
-				assert.Equal(t, "", cordoned, "at most one node cordoned at a time")
```
Comment (johngmyers) [inline pkg/instancegroups/rollingupdate_test.go:225]: I'm wondering if it would be worthwhile to hook into the `TerminateInstances()` mock in order to keep all of the `testingclient.DeleteAction` assertions.

Comment (olemarkus) [reply pkg/instancegroups/rollingupdate_test.go:225]: I thought about it, but it _shouldn't_ actually delete any nodes, so seems strange to test for it.
We are also checking that the ASGs are empty at the end, so we know the terminations take place.

File: pkg/instancegroups/instancegroups.go [hunk 2]
```diff
@@ -409,9 +410,8 @@ func (c *RollingUpdateCluster) drainTerminateAndWait(u *cloudinstances.CloudInst
 		}
 	}
 
-	// We unregister the node before deleting it; if the replacement comes up with the same name it would otherwise still be cordoned
-	// (It often seems like GCE tries to re-use names)
-	if !isBastion && !c.CloudOnly {
+	// GCE often re-uses names, so we delete the node object to prevent the new instance from using the cordoned Node object
+	if kops.CloudProviderID(c.Cluster.Spec.CloudProvider) == kops.CloudProviderGCE && !isBastion && !c.CloudOnly {
```
Comment (hakman) [inline pkg/instancegroups/instancegroups.go:414]:
```suggestion
	if api.CloudProviderID(c.Cluster.Spec.CloudProvider) == kops.CloudProviderGCE && !isBastion && !c.CloudOnly {
```

File: pkg/instancegroups/instancegroups.go [hunk 3]
```diff
@@ -36,6 +36,7 @@ import (
 	"k8s.io/klog/v2"
 	"k8s.io/kubectl/pkg/drain"
 
+	"k8s.io/kops/pkg/apis/kops"
```
Comment (hakman) [inline pkg/instancegroups/instancegroups.go:39]: Already declared below.
```suggestion
```

**Review by hakman — CHANGES_REQUESTED** [review]

**Review by hakman — APPROVED** [review]
