### PR TITLE
Cilium etcd fixes

### LINKED ISSUE #10663: Cilium-dedicated etcd is reaching space quota limit without AUTO_COMPACTION
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

```
1.18.2 (git-84495481e4)
```

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

```json
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-11-25T13:19:56Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"89182bdd065fbcaffefec691908a739d161efc03", GitTreeState:"clean", BuildDate:"2020-12-18T12:02:35Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**3. What cloud provider are you using?**
```
AWS
```

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

Create a new cluster using cilium dedicated etcd created with etcd-manager and wait for a few days.

**5. What happened after the commands executed?**

Without AUTO_COMPACTION options configured, after a few days, the etcd cluster reaches its space quota limit of 2Gb, and Cilium stops working with the following message:
```
# snippet of cilium pod log
level=fatal msg="Unable to connect to kvstore" error="etcdserver: mvcc: database space exceeded" module=etcd subsys=kvstore
```

The etcd cluster reports the following alert:
```
memberID:2157140721128943973 alarm:NOSPACE 
memberID:17459609605570688463 alarm:NOSPACE
```

**6. What did you expect to happen?**

If I edit my cluster and add the following environment variables to the manager configuration, it starts working as expected
```
# snippet cluster.yaml spec for etcdClusters item.
  - name: cilium
    version: 3.3.10
    manager:
      env:
      - name: ETCD_AUTO_COMPACTION_MODE
        value: revision
      - name: ETCD_AUTO_COMPACTION_RETENTION
        value: "1000"
```

Then I could see this cluster reporting:
```
2021-01-26 19:40:54.223524 I | pkg/flags: recognized and used environment variable ETCD_AUTO_COMPACTION_MODE=revision
2021-01-26 19:40:54.223530 I | pkg/flags: recognized and used environment variable ETCD_AUTO_COMPACTION_RETENTION=1000
```

It's likely to be a default option for all etcd clusters, or at least kops should have a section about this in the documentation, especially for Cilium configuration.

### PR DESCRIPTION
**Pull request by olemarkus**
First commit fixes an issue where the status object of the CNP becomes too large to write to etcd. Also enables "scalability"
Second fixes #10663

### CODE REVIEW

File: upup/pkg/fi/cloudup/new_cluster.go [hunk 1]
```diff
@@ -1173,6 +1173,19 @@ func createEtcdCluster(etcdCluster string, masters []*api.InstanceGroup, encrypt
...
 		etcd.Members = append(etcd.Members, m)
 	}
+
+	// Cilium etcd server is not compacted by the k8s API server.
+	if etcd.Name == "cilium" {
+		if etcd.Manager == nil {
+			etcd.Manager = &api.EtcdManagerSpec{
+				Env: []api.EnvVar{
+					{Name: "ETCD_AUTO_COMPACTION_MODE", Value: "revision"},
+					{Name: "ETCD_AUTO_COMPACTION_RETENTION", Value: "2500"},
```
Comment (johngmyers) [inline upup/pkg/fi/cloudup/new_cluster.go:1183]: Perhaps we should enable this for existing clusters?

Comment (olemarkus) [reply upup/pkg/fi/cloudup/new_cluster.go:1183]: The way this is managed with env vars makes it a bit tricky. There is no way of saying "I want to manage this myself".

We could maybe highlight this more in release notes.

Comment (johngmyers) [reply upup/pkg/fi/cloudup/new_cluster.go:1183]: We could take any value explicitly mentioned in the spec as overriding. That leaves the problem of "I want to omit this environment variable", but that has some possible solutions.

Comment (olemarkus) [reply upup/pkg/fi/cloudup/new_cluster.go:1183]: Perhaps merge this one and cherry-pick to 1.21 and then have a longer ponder on how to set these by default for existing clusters.

Comment (johngmyers) [reply upup/pkg/fi/cloudup/new_cluster.go:1183]: The disadvantage of that would be that clusters created in the interim would get these values set in the cluster spec, making it harder to change the defaults later. But perhaps it's an obscure enough feature.

Comment (olemarkus) [reply upup/pkg/fi/cloudup/new_cluster.go:1183]: These defaults should be fine (same as cilium-etcd-operator used before it got deprecated). For clusters that needs something else, their cluster operators should know what to do.

**Review by johngmyers — APPROVED** [review]

**Comment by eddycharly** [comment]
Isn't periodic defragmentation necessary too ?

**Comment by olemarkus** [comment]
Drefrag will just reclaim disk space. Since we use dedicated disks for etcd, it probably is not worth the cost of freezing the etcd node regularly.
