### PR TITLE
Tolerate concurrent deletion errors

### LINKED ISSUE #1614: kops delete cluster with region failing
Example was:

```
kops delete cluster test-c-cluster.k8s-test.example.com --yes --region=eu-west-1
```

### PR DESCRIPTION
**Pull request by justinsb**
Ignore the specific error codes reported as happening during concurrent
cluster deletion.

Fix #1614

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1694)

### CODE REVIEW

File: upup/pkg/kutil/delete_cluster.go [hunk 1]
```diff
@@ -565,6 +565,10 @@ func DeleteSecurityGroup(cloud fi.Cloud, t *ResourceTracker) error {
 		}
 		response, err := c.EC2().DescribeSecurityGroups(request)
 		if err != nil {
+			if awsup.AWSErrorCode(err) == "InvalidGroup.NotFound" {
```
Comment (chrislovecnm) [inline upup/pkg/kutil/delete_cluster.go]: Can this string: `"InvalidGroup.NotFound"` be replaced with a value in AWS api?  My concern is that they refactor the message, i.e. change their contract.  Our code would not be smart enough to pick up the changes.

Comment (justinsb) [inline upup/pkg/kutil/delete_cluster.go]: The code shouldn't change; it would break a lot of clients.  I agree aws-sdk-go should export it, but they don't.  Arguably though, what would they call it - `InvalidGroupNotFound`?
