### PR TITLE
Fix OpenStack delete functions

### LINKED ISSUE #10724: [OpenStack] Ensure that instances are really deleted
**1. What `kops` version are you running? The command `kops version`, will display
 this information.** master

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.** 1.20.2

**3. What cloud provider are you using?** openstack

**4. What commands did you run?  What is the simplest way to reproduce this issue?** kops delete cluster --yes

**5. What happened after the commands executed?**

```
TYPE        NAME                            ID
Instance    master-espsti-xsne6w                    811012ca-47dd-4897-8b7e-ec075cf77ebb
Instance    nodes-espsti-1vjn3k                    4bc4d503-970f-428f-aceb-236d1059a870
Volume        espsti.etcd-events.x-bouncer-dev.k8s.local    9ae29d60-6fa3-4973-9823-02d4c68ea6af
Volume        espsti.etcd-main.x-bouncer-dev.k8s.local        3d8993ac-7100-4d90-8a37-6c43e0ab5015

Instance:4bc4d503-970f-428f-aceb-236d1059a870    ok
Instance:811012ca-47dd-4897-8b7e-ec075cf77ebb    ok
Volume:3d8993ac-7100-4d90-8a37-6c43e0ab5015    error deleting resources, will retry: error deleting volume: Bad request with: [DELETE https://foobar.com:13776/v3/72b0f3799ced4ba1845bbc0a825d0fff/volumes/3d8993ac-7100-4d90-8a37-6c43e0ab5015], error message: {"badRequest": {"code": 400, "message": "Invalid volume: Volume status must be available or error or error_restoring or error_extending or error_managing and must not be migrating, attached, belong to a group, have snapshots or be disassociated from snapshots after volume transfer."}}
Volume:9ae29d60-6fa3-4973-9823-02d4c68ea6af    error deleting resources, will retry: error deleting volume: Bad request with: [DELETE https://foobar.com:13776/v3/72b0f3799ced4ba1845bbc0a825d0fff/volumes/9ae29d60-6fa3-4973-9823-02d4c68ea6af], error message: {"badRequest": {"code": 400, "message": "Invalid volume: Volume status must be available or error or error_restoring or error_extending or error_managing and must not be migrating, attached, belong to a group, have snapshots or be disassociated from snapshots after volume transfer."}}
Not all resources deleted; waiting before reattempting deletion
    Volume:9ae29d60-6fa3-4973-9823-02d4c68ea6af
    Volume:3d8993ac-7100-4d90-8a37-6c43e0ab5015
Volume:3d8993ac-7100-4d90-8a37-6c43e0ab5015    error deleting resources, will retry: error deleting volume: Bad request with: [DELETE https://foobar.com:13776/v3/72b0f3799ced4ba1845bbc0a825d0fff/volumes/3d8993ac-7100-4d90-8a37-6c43e0ab5015], error message: {"badRequest": {"code": 400, "message": "Invalid volume: Volume status must be available or error or error_restoring or error_extending or error_managing and must not be migrating, attached, belong to a group, have snapshots or be disassociated from snapshots after volume transfer."}}
Volume:9ae29d60-6fa3-4973-9823-02d4c68ea6af    error deleting resources, will retry: error deleting volume: Bad request with: [DELETE https://foobar.com:13776/v3/72b0f3799ced4ba1845bbc0a825d0fff/volumes/9ae29d60-6fa3-4973-9823-02d4c68ea6af], error message: {"badRequest": {"code": 400, "message": "Invalid volume: Volume status must be available or error or error_restoring or error_extending or error_managing and must not be migrating, attached, belong to a group, have snapshots or be disassociated from snapshots after volume transfer."}}
Not all resources deleted; waiting before reattempting deletion
    Volume:9ae29d60-6fa3-4973-9823-02d4c68ea6af
    Volume:3d8993ac-7100-4d90-8a37-6c43e0ab5015
Volume:9ae29d60-6fa3-4973-9823-02d4c68ea6af    error deleting resources, will retry: error deleting volume: Bad request with: [DELETE https://foobar.com:13776/v3/72b0f3799ced4ba1845bbc0a825d0fff/volumes/9ae29d60-6fa3-4973-9823-02d4c68ea6af], error message: {"badRequest": {"code": 400, "message": "Invalid volume: Volume status must be available or error or error_restoring or error_extending or error_managing and must not be migrating, attached, belong to a group, have snapshots or be disassociated from snapshots after volume transfer."}}
Volume:3d8993ac-7100-4d90-8a37-6c43e0ab5015    error deleting resources, will retry: error deleting volume: Bad request with: [DELETE https://foobar.com:13776/v3/72b0f3799ced4ba1845bbc0a825d0fff/volumes/3d8993ac-7100-4d90-8a37-6c43e0ab5015], error message: {"badRequest": {"code": 400, "message": "Invalid volume: Volume status must be available or error or error_restoring or error_extending or error_managing and must not be migrating, attached, belong to a group, have snapshots or be disassociated from snapshots after volume transfer."}}
Not all resources deleted; waiting before reattempting deletion
    Volume:9ae29d60-6fa3-4973-9823-02d4c68ea6af
    Volume:3d8993ac-7100-4d90-8a37-6c43e0ab5015
```

currently when we delete servers in OpenStack, we do not check does it really delete anything. Deleting server in OpenStack is async function (https://docs.openstack.org/api-ref/compute/?expanded=delete-server-detail#delete-server), which means that API response code means that request has been added to queue. However, for instance packer solves this problem by following: 

1) delete server
2) send GET requests for a while to see is server really deleted

Like in this example case, it says that instances are deleted. However, the whole physical nova was missing from internet, so its impossible that those were deleted.

**6. What did you expect to happen?**

I expect that we should also send GET request to see did it really delete the instance.

https://github.com/kubernetes/kops/blob/master/upup/pkg/fi/cloudup/openstack/instance.go#L154

if err == nil we should GET instance for a while inside RetryWithBackoff

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

### PR DESCRIPTION
**Pull request by ottosulin**
This PR fixes #10724 with these two changes:

1) Add missing RetryWithBackoff to DeleteInstanceWithID
2) Fix broken retry logic in all other delete functions. In the current implementation, as the first Delete request will almost certainly return nil, the function will return true and the retry will not try again, resulting in potentially some assets not getting deleted from OpenStack

Also, the current writeBackoff is a bit too aggressive and I introduced less hasty deleteBackoff.

The change has been tested with OpenStack. I verified that all APIs we are hitting will eventually return the 404 (type) we are looking for.

### CODE REVIEW

**Comment by zetaab** [comment]
please remove k8s.io folder

File: upup/pkg/fi/cloudup/openstack/router.go [hunk 1]
```diff
@@ -127,12 +130,18 @@ func (c *openstackCloud) DeleteRouter(routerID string) error {
 }
 
 func deleteRouter(c OpenstackCloud, routerID string) error {
-	done, err := vfs.RetryWithBackoff(writeBackoff, func() (bool, error) {
+	done, err := vfs.RetryWithBackoff(deleteBackoff, func() (bool, error) {
 		err := routers.Delete(c.NetworkingClient(), routerID).ExtractErr()
+		if err != nil {
```
Comment (zetaab) [inline upup/pkg/fi/cloudup/openstack/router.go:135]: delete this if structure

**Review by zetaab — CHANGES_REQUESTED** [review]

**Review by zetaab — APPROVED** [review]
Thanks for fixing this!

/approve
/lgtm
