### PR TITLE
Disable some flags in kube-apiserver when logging-format is not text

### LINKED ISSUE #13245: kube-apiserver crashes after setting "logFormat: json"
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Client/Server Version 1.22.3

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
kubernetesVersion: 1.21.8

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Edit cluster
Add parameter 
```
spec:
  kubeAPIServer:
    logFormat: json

```
kops update cluster
kops rolling-update cluster --instance-group ```<one of the masters>```
**5. What happened after the commands executed?**

kube-apiserver crashes with log:

```
Flag --insecure-port has been deprecated, This flag has no effect now and will be removed in v1.24.
I0209 10:06:51.271270       1 flags.go:59] FLAG: --add-dir-header="false"
I0209 10:06:51.271471       1 flags.go:59] FLAG: --address="127.0.0.1"
I0209 10:06:51.271486       1 flags.go:59] FLAG: --admission-control="[]"
I0209 10:06:51.271497       1 flags.go:59] FLAG: --admission-control-config-file=""
I0209 10:06:51.271503       1 flags.go:59] FLAG: --advertise-address="<nil>"
I0209 10:06:51.271508       1 flags.go:59] FLAG: --allow-metric-labels="[]"
I0209 10:06:51.271519       1 flags.go:59] FLAG: --allow-privileged="true"
I0209 10:06:51.271529       1 flags.go:59] FLAG: --alsologtostderr="true"
I0209 10:06:51.271535       1 flags.go:59] FLAG: --anonymous-auth="false"
I0209 10:06:51.271540       1 flags.go:59] FLAG: --api-audiences="[kubernetes.svc.default]"
I0209 10:06:51.271552       1 flags.go:59] FLAG: --apiserver-count="3"
I0209 10:06:51.271559       1 flags.go:59] FLAG: --audit-log-batch-buffer-size="10000"
I0209 10:06:51.271565       1 flags.go:59] FLAG: --audit-log-batch-max-size="1"
I0209 10:06:51.271571       1 flags.go:59] FLAG: --audit-log-batch-max-wait="0s"
I0209 10:06:51.271581       1 flags.go:59] FLAG: --audit-log-batch-throttle-burst="0"
I0209 10:06:51.271586       1 flags.go:59] FLAG: --audit-log-batch-throttle-enable="false"
I0209 10:06:51.271592       1 flags.go:59] FLAG: --audit-log-batch-throttle-qps="0"
I0209 10:06:51.271599       1 flags.go:59] FLAG: --audit-log-compress="false"
I0209 10:06:51.271604       1 flags.go:59] FLAG: --audit-log-format="json"
I0209 10:06:51.271609       1 flags.go:59] FLAG: --audit-log-maxage="10"
I0209 10:06:51.271614       1 flags.go:59] FLAG: --audit-log-maxbackup="1"
I0209 10:06:51.271619       1 flags.go:59] FLAG: --audit-log-maxsize="100"
I0209 10:06:51.271625       1 flags.go:59] FLAG: --audit-log-mode="blocking"
I0209 10:06:51.271630       1 flags.go:59] FLAG: --audit-log-path="/var/log/kube-apiserver-audit.log"
I0209 10:06:51.271636       1 flags.go:59] FLAG: --audit-log-truncate-enabled="false"
I0209 10:06:51.271642       1 flags.go:59] FLAG: --audit-log-truncate-max-batch-size="10485760"
I0209 10:06:51.271652       1 flags.go:59] FLAG: --audit-log-truncate-max-event-size="102400"
I0209 10:06:51.271658       1 flags.go:59] FLAG: --audit-log-version="audit.k8s.io/v1"
I0209 10:06:51.271664       1 flags.go:59] FLAG: --audit-policy-file="/srv/kubernetes/kube-apiserver/audit-policy-config.yaml"
I0209 10:06:51.271670       1 flags.go:59] FLAG: --audit-webhook-batch-buffer-size="10000"
I0209 10:06:51.271675       1 flags.go:59] FLAG: --audit-webhook-batch-initial-backoff="10s"
I0209 10:06:51.271680       1 flags.go:59] FLAG: --audit-webhook-batch-max-size="400"
I0209 10:06:51.271685       1 flags.go:59] FLAG: --audit-webhook-batch-max-wait="30s"
I0209 10:06:51.271691       1 flags.go:59] FLAG: --audit-webhook-batch-throttle-burst="15"
I0209 10:06:51.271695       1 flags.go:59] FLAG: --audit-webhook-batch-throttle-enable="true"
I0209 10:06:51.271700       1 flags.go:59] FLAG: --audit-webhook-batch-throttle-qps="10"
I0209 10:06:51.271705       1 flags.go:59] FLAG: --audit-webhook-config-file=""
I0209 10:06:51.271710       1 flags.go:59] FLAG: --audit-webhook-initial-backoff="10s"
I0209 10:06:51.271715       1 flags.go:59] FLAG: --audit-webhook-mode="batch"
I0209 10:06:51.271720       1 flags.go:59] FLAG: --audit-webhook-truncate-enabled="false"
I0209 10:06:51.271725       1 flags.go:59] FLAG: --audit-webhook-truncate-max-batch-size="10485760"
I0209 10:06:51.271730       1 flags.go:59] FLAG: --audit-webhook-truncate-max-event-size="102400"
I0209 10:06:51.271735       1 flags.go:59] FLAG: --audit-webhook-version="audit.k8s.io/v1"
I0209 10:06:51.271741       1 flags.go:59] FLAG: --authentication-token-webhook-cache-ttl="2m0s"
I0209 10:06:51.271746       1 flags.go:59] FLAG: --authentication-token-webhook-config-file="/etc/kubernetes/authn.config"
I0209 10:06:51.271752       1 flags.go:59] FLAG: --authentication-token-webhook-version="v1beta1"
I0209 10:06:51.271757       1 flags.go:59] FLAG: --authorization-mode="[Node,RBAC]"
I0209 10:06:51.271769       1 flags.go:59] FLAG: --authorization-policy-file=""
I0209 10:06:51.271774       1 flags.go:59] FLAG: --authorization-webhook-cache-authorized-ttl="5m0s"
I0209 10:06:51.271780       1 flags.go:59] FLAG: --authorization-webhook-cache-unauthorized-ttl="30s"
I0209 10:06:51.271785       1 flags.go:59] FLAG: --authorization-webhook-config-file=""
I0209 10:06:51.271790       1 flags.go:59] FLAG: --authorization-webhook-version="v1beta1"
I0209 10:06:51.271795       1 flags.go:59] FLAG: --bind-address="0.0.0.0"
I0209 10:06:51.271800       1 flags.go:59] FLAG: --cert-dir="/var/run/kubernetes"
I0209 10:06:51.271805       1 flags.go:59] FLAG: --client-ca-file="/srv/kubernetes/ca.crt"
I0209 10:06:51.271811       1 flags.go:59] FLAG: --cloud-config="/etc/kubernetes/in-tree-cloud.config"
I0209 10:06:51.271816       1 flags.go:59] FLAG: --cloud-provider="aws"
I0209 10:06:51.271821       1 flags.go:59] FLAG: --cloud-provider-gce-l7lb-src-cidrs="130.211.0.0/22,35.191.0.0/16"
I0209 10:06:51.271832       1 flags.go:59] FLAG: --cloud-provider-gce-lb-src-cidrs="130.211.0.0/22,209.85.152.0/22,209.85.204.0/22,35.191.0.0/16"
I0209 10:06:51.271841       1 flags.go:59] FLAG: --contention-profiling="false"
I0209 10:06:51.271846       1 flags.go:59] FLAG: --cors-allowed-origins="[]"
I0209 10:06:51.271854       1 flags.go:59] FLAG: --default-not-ready-toleration-seconds="300"
I0209 10:06:51.271860       1 flags.go:59] FLAG: --default-unreachable-toleration-seconds="300"
I0209 10:06:51.271865       1 flags.go:59] FLAG: --default-watch-cache-size="100"
I0209 10:06:51.271870       1 flags.go:59] FLAG: --delete-collection-workers="1"
I0209 10:06:51.271882       1 flags.go:59] FLAG: --deserialization-cache-size="0"
I0209 10:06:51.271887       1 flags.go:59] FLAG: --disable-admission-plugins="[]"
I0209 10:06:51.271897       1 flags.go:59] FLAG: --disabled-metrics="[]"
I0209 10:06:51.271903       1 flags.go:59] FLAG: --egress-selector-config-file=""
I0209 10:06:51.271908       1 flags.go:59] FLAG: --enable-admission-plugins="[NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,NodeRestriction,ResourceQuota]"
I0209 10:06:51.271924       1 flags.go:59] FLAG: --enable-aggregator-routing="false"
I0209 10:06:51.271929       1 flags.go:59] FLAG: --enable-bootstrap-token-auth="false"
I0209 10:06:51.271934       1 flags.go:59] FLAG: --enable-garbage-collector="true"
I0209 10:06:51.271939       1 flags.go:59] FLAG: --enable-logs-handler="true"
I0209 10:06:51.271944       1 flags.go:59] FLAG: --enable-priority-and-fairness="true"
I0209 10:06:51.271948       1 flags.go:59] FLAG: --enable-swagger-ui="false"
I0209 10:06:51.271953       1 flags.go:59] FLAG: --encryption-provider-config=""
I0209 10:06:51.271958       1 flags.go:59] FLAG: --endpoint-reconciler-type="lease"
I0209 10:06:51.271963       1 flags.go:59] FLAG: --etcd-cafile="/srv/kubernetes/kube-apiserver/etcd-ca.crt"
I0209 10:06:51.271969       1 flags.go:59] FLAG: --etcd-certfile="/srv/kubernetes/kube-apiserver/etcd-client.crt"
I0209 10:06:51.271976       1 flags.go:59] FLAG: --etcd-compaction-interval="5m0s"
I0209 10:06:51.271981       1 flags.go:59] FLAG: --etcd-count-metric-poll-period="1m0s"
I0209 10:06:51.271987       1 flags.go:59] FLAG: --etcd-db-metric-poll-interval="30s"
I0209 10:06:51.271992       1 flags.go:59] FLAG: --etcd-healthcheck-timeout="2s"
I0209 10:06:51.271997       1 flags.go:59] FLAG: --etcd-keyfile="/srv/kubernetes/kube-apiserver/etcd-client.key"
I0209 10:06:51.272003       1 flags.go:59] FLAG: --etcd-prefix="/registry"
I0209 10:06:51.272008       1 flags.go:59] FLAG: --etcd-servers="[https://127.0.0.1:4001]"
I0209 10:06:51.272016       1 flags.go:59] FLAG: --etcd-servers-overrides="[/events#https://127.0.0.1:4002]"
I0209 10:06:51.272025       1 flags.go:59] FLAG: --event-ttl="1h0m0s"
I0209 10:06:51.272030       1 flags.go:59] FLAG: --experimental-encryption-provider-config=""
I0209 10:06:51.272035       1 flags.go:59] FLAG: --experimental-logging-sanitization="false"
I0209 10:06:51.272040       1 flags.go:59] FLAG: --external-hostname=""
I0209 10:06:51.272044       1 flags.go:59] FLAG: --feature-gates=""
I0209 10:06:51.272053       1 flags.go:59] FLAG: --goaway-chance="0"
I0209 10:06:51.272060       1 flags.go:59] FLAG: --help="false"
I0209 10:06:51.272065       1 flags.go:59] FLAG: --http2-max-streams-per-connection="0"
I0209 10:06:51.272070       1 flags.go:59] FLAG: --identity-lease-duration-seconds="3600"
I0209 10:06:51.272075       1 flags.go:59] FLAG: --identity-lease-renew-interval-seconds="10"
I0209 10:06:51.272080       1 flags.go:59] FLAG: --insecure-bind-address="127.0.0.1"
I0209 10:06:51.272085       1 flags.go:59] FLAG: --insecure-port="0"
I0209 10:06:51.272090       1 flags.go:59] FLAG: --kubelet-certificate-authority=""
I0209 10:06:51.272095       1 flags.go:59] FLAG: --kubelet-client-certificate="/srv/kubernetes/kube-apiserver/kubelet-api.crt"
I0209 10:06:51.272101       1 flags.go:59] FLAG: --kubelet-client-key="/srv/kubernetes/kube-apiserver/kubelet-api.key"
I0209 10:06:51.272107       1 flags.go:59] FLAG: --kubelet-https="true"
I0209 10:06:51.272114       1 flags.go:59] FLAG: --kubelet-port="10250"
I0209 10:06:51.272122       1 flags.go:59] FLAG: --kubelet-preferred-address-types="[InternalIP,Hostname,ExternalIP]"
I0209 10:06:51.272130       1 flags.go:59] FLAG: --kubelet-read-only-port="10255"
I0209 10:06:51.272135       1 flags.go:59] FLAG: --kubelet-timeout="5s"
I0209 10:06:51.272140       1 flags.go:59] FLAG: --kubernetes-service-node-port="0"
I0209 10:06:51.272145       1 flags.go:59] FLAG: --lease-reuse-duration-seconds="60"
I0209 10:06:51.272153       1 flags.go:59] FLAG: --livez-grace-period="0s"
I0209 10:06:51.272158       1 flags.go:59] FLAG: --log-backtrace-at=":0"
I0209 10:06:51.272167       1 flags.go:59] FLAG: --log-dir=""
I0209 10:06:51.272173       1 flags.go:59] FLAG: --log-file="/var/log/kube-apiserver.log"
I0209 10:06:51.272179       1 flags.go:59] FLAG: --log-file-max-size="1800"
I0209 10:06:51.272184       1 flags.go:59] FLAG: --log-flush-frequency="5s"
I0209 10:06:51.272189       1 flags.go:59] FLAG: --logging-format="json"
I0209 10:06:51.272194       1 flags.go:59] FLAG: --logtostderr="false"
I0209 10:06:51.272200       1 flags.go:59] FLAG: --master-service-namespace="default"
I0209 10:06:51.272204       1 flags.go:59] FLAG: --max-connection-bytes-per-sec="0"
I0209 10:06:51.272209       1 flags.go:59] FLAG: --max-mutating-requests-inflight="200"
I0209 10:06:51.272214       1 flags.go:59] FLAG: --max-requests-inflight="400"
I0209 10:06:51.272219       1 flags.go:59] FLAG: --min-request-timeout="1800"
I0209 10:06:51.272224       1 flags.go:59] FLAG: --oidc-ca-file=""
I0209 10:06:51.272229       1 flags.go:59] FLAG: --oidc-client-id=""
I0209 10:06:51.272233       1 flags.go:59] FLAG: --oidc-groups-claim=""
I0209 10:06:51.272238       1 flags.go:59] FLAG: --oidc-groups-prefix=""
I0209 10:06:51.272242       1 flags.go:59] FLAG: --oidc-issuer-url=""
I0209 10:06:51.272247       1 flags.go:59] FLAG: --oidc-required-claim=""
I0209 10:06:51.272255       1 flags.go:59] FLAG: --oidc-signing-algs="[RS256]"
I0209 10:06:51.272265       1 flags.go:59] FLAG: --oidc-username-claim="sub"
I0209 10:06:51.272270       1 flags.go:59] FLAG: --oidc-username-prefix=""
I0209 10:06:51.272275       1 flags.go:59] FLAG: --one-output="false"
I0209 10:06:51.272280       1 flags.go:59] FLAG: --permit-address-sharing="false"
I0209 10:06:51.272285       1 flags.go:59] FLAG: --permit-port-sharing="false"
I0209 10:06:51.272290       1 flags.go:59] FLAG: --port="0"
I0209 10:06:51.272295       1 flags.go:59] FLAG: --profiling="true"
I0209 10:06:51.272300       1 flags.go:59] FLAG: --proxy-client-cert-file="/srv/kubernetes/kube-apiserver/apiserver-aggregator.crt"
I0209 10:06:51.272309       1 flags.go:59] FLAG: --proxy-client-key-file="/srv/kubernetes/kube-apiserver/apiserver-aggregator.key"
I0209 10:06:51.272316       1 flags.go:59] FLAG: --request-timeout="1m0s"
I0209 10:06:51.272321       1 flags.go:59] FLAG: --requestheader-allowed-names="[aggregator]"
I0209 10:06:51.272329       1 flags.go:59] FLAG: --requestheader-client-ca-file="/srv/kubernetes/kube-apiserver/apiserver-aggregator-ca.crt"
I0209 10:06:51.272338       1 flags.go:59] FLAG: --requestheader-extra-headers-prefix="[X-Remote-Extra-]"
I0209 10:06:51.272346       1 flags.go:59] FLAG: --requestheader-group-headers="[X-Remote-Group]"
I0209 10:06:51.272357       1 flags.go:59] FLAG: --requestheader-username-headers="[X-Remote-User]"
I0209 10:06:51.272366       1 flags.go:59] FLAG: --runtime-config=""
I0209 10:06:51.272377       1 flags.go:59] FLAG: --secure-port="443"
I0209 10:06:51.272382       1 flags.go:59] FLAG: --service-account-api-audiences="[kubernetes.svc.default]"
I0209 10:06:51.272389       1 flags.go:59] FLAG: --service-account-extend-token-expiration="true"
I0209 10:06:51.272394       1 flags.go:59] FLAG: --service-account-issuer="https://api.test.nvsrc.com"
I0209 10:06:51.272404       1 flags.go:59] FLAG: --service-account-jwks-uri="https://api.test.nvsrc.com/openid/v1/jwks"
I0209 10:06:51.272410       1 flags.go:59] FLAG: --service-account-key-file="[/srv/kubernetes/kube-apiserver/service-account.pub]"
I0209 10:06:51.272425       1 flags.go:59] FLAG: --service-account-lookup="true"
I0209 10:06:51.272430       1 flags.go:59] FLAG: --service-account-max-token-expiration="0s"
I0209 10:06:51.272434       1 flags.go:59] FLAG: --service-account-signing-key-file="/srv/kubernetes/kube-apiserver/service-account.key"
I0209 10:06:51.272441       1 flags.go:59] FLAG: --service-cluster-ip-range="100.64.0.0/13"
I0209 10:06:51.272446       1 flags.go:59] FLAG: --service-node-port-range="30000-32767"
I0209 10:06:51.272461       1 flags.go:59] FLAG: --show-hidden-metrics-for-version=""
I0209 10:06:51.272466       1 flags.go:59] FLAG: --shutdown-delay-duration="0s"
I0209 10:06:51.272470       1 flags.go:59] FLAG: --skip-headers="false"
I0209 10:06:51.272475       1 flags.go:59] FLAG: --skip-log-headers="false"
I0209 10:06:51.272480       1 flags.go:59] FLAG: --ssh-keyfile=""
I0209 10:06:51.272485       1 flags.go:59] FLAG: --ssh-user=""
I0209 10:06:51.272490       1 flags.go:59] FLAG: --stderrthreshold="2"
I0209 10:06:51.272495       1 flags.go:59] FLAG: --storage-backend="etcd3"
I0209 10:06:51.272500       1 flags.go:59] FLAG: --storage-media-type="application/vnd.kubernetes.protobuf"
I0209 10:06:51.272505       1 flags.go:59] FLAG: --strict-transport-security-directives="[]"
I0209 10:06:51.272512       1 flags.go:59] FLAG: --target-ram-mb="0"
I0209 10:06:51.272517       1 flags.go:59] FLAG: --tls-cert-file="/srv/kubernetes/kube-apiserver/server.crt"
I0209 10:06:51.272523       1 flags.go:59] FLAG: --tls-cipher-suites="[]"
I0209 10:06:51.272532       1 flags.go:59] FLAG: --tls-min-version=""
I0209 10:06:51.272537       1 flags.go:59] FLAG: --tls-private-key-file="/srv/kubernetes/kube-apiserver/server.key"
I0209 10:06:51.272543       1 flags.go:59] FLAG: --tls-sni-cert-key="[]"
I0209 10:06:51.272550       1 flags.go:59] FLAG: --token-auth-file=""
I0209 10:06:51.272555       1 flags.go:59] FLAG: --v="2"
I0209 10:06:51.272560       1 flags.go:59] FLAG: --version="false"
I0209 10:06:51.272568       1 flags.go:59] FLAG: --vmodule=""
I0209 10:06:51.272573       1 flags.go:59] FLAG: --watch-cache="true"
I0209 10:06:51.272578       1 flags.go:59] FLAG: --watch-cache-sizes="[]"
I0209 10:06:51.272948       1 server.go:629] external host was not specified, using 10.40.164.107
Error: [non-default logging format doesn't honor flag: alsologtostderr, non-default logging format doesn't honor flag: log_file, non-default logging format doesn't honor flag: logtostderr]
```

**6. What did you expect to happen?**

Expecting to get kube-apiserver logs in json format

### PR DESCRIPTION
**Pull request by h3poteto**
Fixes #13245 

Disable these flags because these are not accepted when I use `json` as `logging-format`.

* `--logtostderr`
* `--alsologtostderr`
* `--log-file`

According to Kubernetes document: 
> Non-default formats don't honor these flags: --add-dir-header, --alsologtostderr, --log-backtrace-at, --log-dir, --log-file, --log-file-max-size, --logtostderr, --one-output, --skip-headers, --skip-log-headers, --stderrthreshold, --vmodule.

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/

And when I specify these flags, kube-apiserver says an error.

### CODE REVIEW

File: nodeup/pkg/model/kube_apiserver.go [hunk 1]
```diff
@@ -638,11 +638,17 @@ func (b *KubeAPIServerBuilder) buildPod(kubeAPIServer *kops.KubeAPIServerConfig)
 		container.Args = append(container.Args, sortedStrings(flags)...)
 	} else {
 		container.Command = []string{"/usr/local/bin/kube-apiserver"}
-		container.Args = append(
-			sortedStrings(flags),
-			"--logtostderr=false", // https://github.com/kubernetes/klog/issues/60
-			"--alsologtostderr",
-			"--log-file=/var/log/kube-apiserver.log")
+		if kubeAPIServer.LogFormat != "" && kubeAPIServer.LogFormat != "text" {
```
Comment (hakman) [inline nodeup/pkg/model/kube_apiserver.go:641]: Should this be done for `b.IsKubernetesGTE("1.23")` too?

Comment (h3poteto) [reply nodeup/pkg/model/kube_apiserver.go:641]: No, when Kubernetes version is greater than 1.23, we use `go-runner` and we don't specify these logging options as kube-apiserver's flags. So it is no problem.

**Review by hakman — APPROVED** [review]
