### PR TITLE
do not create egress rules when using vipacl octavia

### LINKED ISSUE #10060: OpenStack SecurityGroupRule Missing input for argument [SecGroupID]
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

1.19.0 alpha 5

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.19.2

**3. What cloud provider are you using?**

openstack (train)

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
kops create cluster \
  --cloud openstack \
  --name v3.k8s.local \
  --state ${KOPS_STATE_STORE} \
  --zones espsti,esptnl,helpa \
  --network-cidr 10.1.0.0/16 \
  --image debian-10 \
  --master-count=3 \
  --node-count=2 \
  --node-size m1.medium \
  --master-size m1.medium \
  --etcd-storage-type solidfire \
  --topology private \
  --bastion \
  --networking calico \
  --api-loadbalancer-type public \
  --os-octavia=true \
  --os-ext-net external \
  --os-ext-subnet ext-ha-v4 \
  --os-lb-floating-subnet ext-ha-v4
```

**5. What happened after the commands executed?**

in logs I can see rows:
```
W1016 13:41:45.651864   85380 executor.go:131] error running task "SecurityGroupRule/IPv6-egress-AllProtos-from-api.v3.k8s.local-to-ANY-0-0" (9m28s remaining to succeed): error creating SecurityGroupRule in SG api.v3.k8s.local: error creating security group rule {egress  IPv6  0 0    }: Missing input for argument [SecGroupID]
```

/area provider/openstack
/kind bug

### PR DESCRIPTION
**Pull request by zetaab**
fixes #10060

### CODE REVIEW

File: pkg/model/openstackmodel/firewall.go [hunk 1]
```diff
@@ -539,8 +539,11 @@ func (b *FirewallModelBuilder) getExistingRules(sgMap map[string]*openstacktasks
 
 }
 
-func (b *FirewallModelBuilder) addDefaultEgress(c *fi.ModelBuilderContext, sgMap map[string]*openstacktasks.SecurityGroup) {
-	for _, sg := range sgMap {
+func (b *FirewallModelBuilder) addDefaultEgress(c *fi.ModelBuilderContext, sgMap map[string]*openstacktasks.SecurityGroup, useVIPACL bool) {
+	for name, sg := range sgMap {
+		if useVIPACL && name == b.Cluster.Spec.MasterPublicName {
```
Comment (zetaab) [inline pkg/model/openstackmodel/firewall.go:544]: when using VIPACL the api.<clustername> securitygroup is not created at all, so we should not add these rules. See https://github.com/kubernetes/kops/blob/master/pkg/model/openstackmodel/firewall.go#L573-L584

**Comment by zetaab** [comment]
/test pull-kops-e2e-kubernetes-aws
--
