### PR TITLE
Fix DNS name precreation

### LINKED ISSUE #1393: Weird DNS names being created for etcd
Seeing these records:

```
route53-record          etcd-events-us-east-1c.internal.api.calico.example.com.                         Z1QIKPN5SWH8LO/etcd-events-us-east-1c.internal.api.calico.example.com.
route53-record          etcd-events-us-east-1c.internal.calico.example.com.                             Z1QIKPN5SWH8LO/etcd-events-us-east-1c.internal.calico.example.com.
````

Pretty sure we shouldn't have both.

### PR DESCRIPTION
**Pull request by justinsb**
We were creating the wrong names for etcd.  Also add a test.

Fix #1393

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1396)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
Need to not be on my phone to review.

File: upup/pkg/fi/cloudup/dns.go [hunk 1]
```diff
@@ -121,38 +121,18 @@ func precreateDNS(cluster *api.Cluster, cloud fi.Cloud) error {
...
-		glog.Warningf("cannot pre-create MasterPublicName - not set")
-	}
+	dnsHostnames := buildPrecreateDNSHostnames(cluster)
 
-	if cluster.Spec.MasterInternalName != "" {
-		dnsHostnames = append(dnsHostnames, cluster.Spec.MasterInternalName)
-	} else {
-		glog.Warningf("cannot pre-create MasterInternalName - not set")
+	if len(dnsHostnames) == 0 {
+		glog.Infof("No DNS records to pre-create")
```
Comment (chrislovecnm) [inline upup/pkg/fi/cloudup/dns.go]: What log level is Infof V(2)?

File: upup/pkg/fi/cloudup/dns.go [hunk 2]
```diff
@@ -216,3 +196,36 @@ func precreateDNS(cluster *api.Cluster, cloud fi.Cloud) error {
...
+// buildPrecreateDNSHostnames returns the hostnames we should precreate
+func buildPrecreateDNSHostnames(cluster *api.Cluster) []string {
+	dnsInternalSuffix := ".internal." + cluster.ObjectMeta.Name
+
+	var dnsHostnames []string
+
+	if cluster.Spec.MasterPublicName != "" {
+		dnsHostnames = append(dnsHostnames, cluster.Spec.MasterPublicName)
+	} else {
+		glog.Warningf("cannot pre-create MasterPublicName - not set")
```
Comment (chrislovecnm) [inline upup/pkg/fi/cloudup/dns.go]: Are going to get this warning every time wit private topo?

File: upup/pkg/fi/cloudup/dns.go [hunk 3]
```diff
@@ -216,3 +196,36 @@ func precreateDNS(cluster *api.Cluster, cloud fi.Cloud) error {
...
+	}
+
+	if cluster.Spec.MasterInternalName != "" {
+		dnsHostnames = append(dnsHostnames, cluster.Spec.MasterInternalName)
+	} else {
+		glog.Warningf("cannot pre-create MasterInternalName - not set")
```
Comment (chrislovecnm) [inline upup/pkg/fi/cloudup/dns.go]: Should we fail? Or log it as an error?

File: upup/pkg/fi/cloudup/dns.go (hunk 2 above)
Comment (justinsb) [inline upup/pkg/fi/cloudup/dns.go]: If we do we'll fix it :-)

File: upup/pkg/fi/cloudup/dns.go (hunk 1 above)
Comment (justinsb) [inline upup/pkg/fi/cloudup/dns.go]: 2

File: upup/pkg/fi/cloudup/dns.go (hunk 3 above)
Comment (justinsb) [inline upup/pkg/fi/cloudup/dns.go]: We log it as a warning.  We certainly shouldn't fail everything ... we might well not have permissions on this IAM account or something.  Warning seems appropriate given we aren't stopping.

**Comment by chrislovecnm** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kops/1396)*

**Comment by chrislovecnm** [comment]
/lgtm

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kops/1396#-:-Ka0-cgw9BjFsXh9JMQZ:b-8ks5qa)*

**Comment by chrislovecnm** [comment]
We need the bots :(

**Comment by zmerlynn** [comment]
@chrislovecnm: Which bots? The main thing we're missing is a full instance of the submit queue, but it doesn't buy us much.
