### PR TITLE
Resolve DNS Hosted Zone ID while building IAM policy

### LINKED ISSUE #1949: New Route53 RolePolicy has incorrectly generated hosted zone arn for `Resource`
## Issue

The new Route53 RolePolicy for masters, added in [this PR](https://github.com/kubernetes/kops/pull/1871/files) uses `"arn:aws:route53:::hostedzone/" + b.Cluster.Spec.DNSZone` as the value for the `Resource` property in the policy.

If `dnsZone:` (`Spec.DNSZone`) is the hosted zone's name (like `cluster.example.com`), the correct hosted zone id isn't looked up and the generated `Resource` is an invalid arn.

`dns-controller` then attempts to `ListResourceRecordSets` against the valid arn for that hosted zone (something like `arn:aws:route53:::hostedzone/ABCDEFGHIJKL`) and is denied. 

## Fix

The fix is to, if `dnsZone` is a hosted zone name, use the HostedZoneId in the arn generation, otherwise use the provided `dnsZone` property.

There's a function [`findZone`](https://github.com/kubernetes/kops/blob/master/dns-controller/pkg/dns/dnscontroller.go#L361) that already uses the correct logic to return the zone's id.

## Workaround

If you run into this issue and find this page via google, simply use the hosted zone's id instead of the name for `dnsZone` in the cluster state file.

### PR DESCRIPTION
**Pull request by zytek**
Fixes #1949 by resolving DNS Zone prior to running IAM builder.

Also small refactor to remove code duplication (thanks @yissachar )

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kops/1969)

### CODE REVIEW

**Comment by zytek** [comment]
rebased to pull in fixes for CI

File: pkg/model/iam/iam_builder.go [hunk 1]
```diff
@@ -212,6 +175,26 @@ func (b *IAMPolicyBuilder) BuildAWSIAMPolicy() (*IAMPolicy, error) {
 		}
 	}
 
+	p.Statement = append(p.Statement, &IAMStatement{
```
Comment (justinsb) [inline pkg/model/iam/iam_builder.go]: Moving this is great - the code repetition is less acceptable given the route53 policies are no longer trivial.  But this is what is breaking the cloudformation test, because the order of the rules has changed.

A few options I think:

* Don't do the refactor
* Fix the test (it shouldn't be too bad, just rearranging the sections mostly)
* Pull this into a function and call it twice

File: upup/pkg/fi/cloudup/apply_cluster.go [hunk 2]
```diff
@@ -346,6 +346,8 @@ func (c *ApplyClusterCmd) Run() error {
 	if err != nil {
 		return err
 	}
+	dnszone, _ := findZone(cluster, cloud) // any errors would be already caught in validateDNS
```
Comment (justinsb) [inline upup/pkg/fi/cloudup/apply_cluster.go]: Can we check the error - even if it shouldn't happen?  We do make calls to the cloud APIs, so I think it is possible that things fail the second time (e.g. rate limits).

**Comment by justinsb** [comment]
LGTM.  We have to get the tests passing, and also I always worry about not checking errors, but generally great - thank you - nice fix!

**Comment by justinsb** [comment]
(sorry, hit the wrong button!)

**Comment by zytek** [comment]
* fixed cloudformation template
* fixed error checking when calling findZone (yeah, that wasn't smart to ignore error in function calling external APIs)

CI still fails on my end due to
```
Boilerplate header is wrong for: /Users/zytek/go/src/k8s.io/kops/out/production/kops/upup/models/bindata.go
Execute hack/update-header.sh to update headers
```

but this seems unrelated to my changes. Fails even after rebasing to current master. 


thx @justinsb !

**Comment by justinsb** [comment]
@k8s-bot ok to test
