### PR TITLE
Make CPU Requests for Calico configurable instead of hard-coded

### LINKED ISSUE #7930: Calico cpu request is insufficient on a heavily utilized node causing crashback loop
**1. What `kops` version are you running? `1.14.0`

**2. What Kubernetes version are you running? `v1.14.6`

**3. What cloud provider are you using?** AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**  m4.large node that is 100% utilized 

**5. What happened after the commands executed?**  Calico fails liveness probes causing it to go into a crashback loop

**6. What did you expect to happen?**  Calico to keep running

I understand why the calico requests were reduced, but it will likely be helpful to make it configurable so it can be overridden when someone is using a large node type.  

```
  Warning  Unhealthy  87m (x15 over 96m)     kubelet, ip-10-40-11-0.us-west-2.compute.internal  Readiness probe failed: calico/node is not ready: felix is not ready: Get http://localhost:9099/readiness: dial tcp [::1]:9099: connect: connection refused
  Normal   Started    72m (x11 over 112m)    kubelet, ip-10-40-11-0.us-west-2.compute.internal  Started container calico-node
  Warning  Unhealthy  57m (x10 over 99m)     kubelet, ip-10-40-11-0.us-west-2.compute.internal  Readiness probe failed: calico/node is not ready: felix is not ready: readiness probe reporting 503
  Warning  Unhealthy  27m (x40 over 100m)    kubelet, ip-10-40-11-0.us-west-2.compute.internal  Liveness probe failed: HTTP probe failed with statuscode: 503
  Warning  Unhealthy  17m (x59 over 96m)     kubelet, ip-10-40-11-0.us-west-2.compute.internal  Liveness probe failed: Get http://localhost:9099/liveness: dial tcp 127.0.0.1:9099: connect: connection refused
  Warning  Unhealthy  12m (x105 over 100m)   kubelet, ip-10-40-11-0.us-west-2.compute.internal  Liveness probe failed: Get http://localhost:9099/liveness: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning  BackOff    7m52s (x166 over 84m)  kubelet, ip-10-40-11-0.us-west-2.compute.internal  Back-off restarting failed container
  Warning  Unhealthy  2m52s (x32 over 87m)   kubelet, ip-10-40-11-0.us-west-2.compute.internal  (combined from similar events): Readiness probe failed: calico/node is not ready: BIRD is not ready: BGP not established with 10.40.5.1942019-11-15 16:10:38.576 [INFO][167] readiness.go 88: Number of node(s) with BGP peering established = 15
```

Screen Shot 2019-11-15 at 8 20 54 AM

### PR DESCRIPTION
**Pull request by MoShitrit**
Fixes #7930 

As a side note on Canal- I've noticed that on the templates, the requests differed between k8s versions, where 1.12 had `100m` configured, 1.15 had `250m` and 1.16 had `90m`. Looking at the history of the files, seems like originally there were all created with `250m`, but updates to the 1.12 and 1.16 templates aligned them with the lower requests, while I assume 1.15 was simply overlooked by accident. So to make things simpler and more standardized for documentation - I took the liberty to set all of them to `100m` which is what was intentionally set via this commit - https://github.com/kubernetes/kops/commit/ba76db7f41e7584d156f845197e68308a9050895

I made sure to run `make test` and confirm everything is still passing.
Please let me know if anything seems off, or if anything further is needed.
Thanks! 😄

### CODE REVIEW

**Comment by MoShitrit** [comment]
Trying to figure out why are the tests failing, marking as draft for now.

**Comment by hakman** [comment]
@MoShitrit Run `make goimports` and commit the result. This should fix the CI.
/ok-to-test

**Comment by MoShitrit** [comment]
Hey @hakman,
Yeah I actually tried to run that locally but it doesn't seem to work.
It fails with an error:
```
cannot find module providing package golang.org/x/tools/cmd/goimports: working directory is not part of a module
```

In case it matters, here's the output of `go version`:
```
go version go1.14.2 darwin/amd64
```

**Comment by hakman** [comment]
@MoShitrit any chance you need to set GOPATH?
https://github.com/kubernetes/kops/blob/master/docs/development/building.md

**Comment by MoShitrit** [comment]
@hakman I followed that doc yesterday when I started working on it, actually.
Here's how I'm set up:
```
mosheshitrit:kops mosheshitrit$ echo $GOPATH
/Users/mosheshitrit/kops
mosheshitrit:kops mosheshitrit$ pwd
/Users/mosheshitrit/kops/src/k8s.io/kops
```

And fwiw, here's the output of `go env`:
```
mosheshitrit:kops mosheshitrit$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/mosheshitrit/Library/Caches/go-build"
GOENV="/Users/mosheshitrit/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/mosheshitrit/kops"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.2_1/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.2_1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/mosheshitrit/kops/src/k8s.io/kops/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8d/3cmg2l2j2gl3qpwjv6c3ffrc0000gn/T/go-build753647993=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by MoShitrit** [comment]
@hakman Okay, I figured it out. Looks like the problem was with my local `go` version. I missed the last comment in the troubleshooting session of the building instructions, saying that `kops` supports versions 1.12 or 1.13 (I had 1.14 installed). After downgrading my go version to 1.13, the `make goimports` command ran successfully! 😄 
Thanks for pointing me in the right direction!

**Comment by hakman** [comment]
Happy it all worked out. Check this also and fix the commit message that triggers it.
https://github.com/kubernetes/kops/pull/8987#issuecomment-619504274

**Comment by MoShitrit** [comment]
> Happy it all worked out. Check this also and fix the commit message that triggers it.
> [#8987 (comment)](https://github.com/kubernetes/kops/pull/8987#issuecomment-619504274)

@hakman fixed! The tests are running now, but I ran `make test` locally and made sure everything is passing so I expect to see the same result here.
Marked the PR as `Ready for Review` again.
Please let me know if you see anything else out of order.
Thanks again for all your help!!

File: pkg/apis/kops/networking.go [hunk 1]
```diff
@@ -100,7 +100,9 @@ type FlannelNetworkingSpec struct {
 
 // CalicoNetworkingSpec declares that we want Calico networking
 type CalicoNetworkingSpec struct {
-	CrossSubnet bool `json:"crossSubnet,omitempty"` // Enables Calico's cross-subnet mode when set to true
+	// CPURequest CPU request of Calico container. Default: 100m
+	CPURequest  *resource.Quantity `json:"cpuRequest,omitempty"`
+	CrossSubnet bool               `json:"crossSubnet,omitempty"` // Enables Calico's cross-subnet mode when set to true
```
Comment (hakman) [inline pkg/apis/kops/networking.go:105]: I think this would look better like this
```suggestion
	// CrossSubnet enables Calico's cross-subnet mode when set to true
	CrossSubnet bool `json:"crossSubnet,omitempty"` 
```

File: pkg/apis/kops/v1alpha2/networking.go [hunk 2]
```diff
@@ -100,7 +100,9 @@ type FlannelNetworkingSpec struct {
 
 // CalicoNetworkingSpec declares that we want Calico networking
 type CalicoNetworkingSpec struct {
-	CrossSubnet bool `json:"crossSubnet,omitempty"` // Enables Calico's cross-subnet mode when set to true
+	// CPURequest CPU request of Calico container. Default: 100m
+	CPURequest  *resource.Quantity `json:"cpuRequest,omitempty"`
+	CrossSubnet bool               `json:"crossSubnet,omitempty"` // Enables Calico's cross-subnet mode when set to true
```
Comment (hakman) [inline pkg/apis/kops/v1alpha2/networking.go:105]: I think this would look better like this
```suggestion
	// CrossSubnet enables Calico's cross-subnet mode when set to true 
	CrossSubnet bool `json:"crossSubnet,omitempty"` 
```

**Comment by hakman** [comment]
Thanks @MoShitrit. Looks like it works nicely now.
Please address the small nits I just added and squash the commits when all tests pass. I think one commit would be better for this small change.

**Comment by hakman** [comment]
Also, please change the title to `Make CPU Requests for Calico configurable instead of hard-coded`

It should be enough to link the issue like this:
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

Fixes #7930

**Comment by rifelpet** [comment]
Looks great, thanks!

/lgtm
/approve
