### PR TITLE
Add indent template function and use it to fix KubeDNS.ExternalCoreFile rendering

### LINKED ISSUE #7975: CoreDNS externalCoreFile Parsing Invalid - Indentation
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
`kops 1.15.0`

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
`1.15.6`

**3. What cloud provider are you using?**
`aws`

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
`kops update cluster`

**5. What happened after the commands executed?**
```
error building tasks: error remapping manifest addons/coredns.addons.k8s.io/k8s-1.6.yaml: error parsing yaml: error converting YAML to JSON: yaml: line 10: did not find expected key
```

**6. What did you expect to happen?**
kops to update the addon for CoreDNS to use the `externalCoreFile` value in the `kubedns` fiel

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

Example config:

```yaml
kubeDNS:
    provider: CoreDNS
    externalCoreFile: |
      .:53 {
          forward . 8.8.8.8:53
          log
      }
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**

It looks like the templating is not setup to properly indent the inline doc, as setup here:
https://github.com/kubernetes/kops/pull/7376

We may need an indent function to make this work.

### PR DESCRIPTION
**Pull request by rochacon**
This PR adds a new `indent` template function and use it to fix KubeDNS.ExternalCoreFile rendering as reported on #7975.

`indent` function was copied from [sprig](https://github.com/Masterminds/sprig/blob/v2.17.1/strings.go#L104-L107).

Fixes #7975

### CODE REVIEW

**Comment by rochacon** [comment]
@mikesplain I was able to replace+update a cluster with the following patch using the new externalCoreFile feature. Not sure how we can add a test for this, if you have any idea please let me know so I can include in this PR.

**Comment by mikesplain** [comment]
Awesome thanks! I’ll give this a test later today!

File: upup/pkg/fi/cloudup/template_functions.go [hunk 1]
```diff
@@ -77,6 +77,10 @@ func (tf *TemplateFunctions) AddTo(dest template.FuncMap, secretStore fi.SecretS
 	dest["join"] = func(a []string, sep string) string {
 		return strings.Join(a, sep)
 	}
+	dest["indent"] = func(spaces int, v string) string {
```
Comment (mikesplain) [inline upup/pkg/fi/cloudup/template_functions.go]: This looks pretty good and seems to do the job for me.

Rather than copying the function, would you mind referencing it as we do for our templater in the toolbox?

https://github.com/kubernetes/kops/blob/298f79659a2bd9c1d6548c6c95b335b5e29e6466/pkg/util/templater/templater.go#L76-L92

Comment (rochacon) [reply upup/pkg/fi/cloudup/template_functions.go]: My initial approach was this:

```diff
diff --git pkg/templates/templates.go pkg/templates/templates.go
index 8c92208fb..78e31e5fe 100644
--- pkg/templates/templates.go
+++ pkg/templates/templates.go
@@ -28,6 +28,8 @@ import (
        "k8s.io/kops/pkg/apis/kops"
        "k8s.io/kops/upup/pkg/fi"
        "k8s.io/kops/util/pkg/vfs"
+
+       "github.com/Masterminds/sprig"
 )

 type Templates struct {
@@ -98,7 +100,7 @@ func (t *Templates) loadFrom(base vfs.Path) error {
 func (l *Templates) executeTemplate(key string, d string) (string, error) {
        t := template.New(key)

-       funcMap := make(template.FuncMap)
+       funcMap := sprig.TxtFuncMap()
        //funcMap["Args"] = func() []string {
        //      return args
        //}
```

which fixes the issue. But then I saw `upup/pkg/fi/cloudup.TemplateFunctions.AddTo` and thought it would be too out of scope to replace the base `template.FuncMap` for the main templates package.

Also, there is a few places adding/replacing `join`, `replace` and other conflicting functions.

If you agree this would be too much out of the scope, another solution could be copying just the `indent` function, like:

```diff
diff --git upup/pkg/fi/cloudup/template_functions.go upup/pkg/fi/cloudup/template_functions.go
index f446a9f0c..cda8ae6c0 100644
--- upup/pkg/fi/cloudup/template_functions.go
+++ upup/pkg/fi/cloudup/template_functions.go
@@ -77,10 +77,9 @@ func (tf *TemplateFunctions) AddTo(dest template.FuncMap, secretStore fi.SecretS
        dest["join"] = func(a []string, sep string) string {
                return strings.Join(a, sep)
        }
+       txtFuncMap := sprig.TxtFuncMap()
+       dest["indent"] = txtFuncMap["indent"]
```



Also, the snippet you sent replaces `sprig.TxtFuncMap()["indent"]` function with another implementation?

Comment (mikesplain) [reply upup/pkg/fi/cloudup/template_functions.go]: Ahh yes great points. Though I'd love to do the first suggestion, since this will likely be cherry picked into 1.15 pretty soon, I'd rather do the smaller scope fix (second).  Anyway to reuse code from other repos, embracing their licenses makes life much better.

Thanks so much

Comment (rochacon) [reply upup/pkg/fi/cloudup/template_functions.go]: Done.

**Comment by mikesplain** [comment]
Awesome! We're making some good progress @rochacon!

I think you need to run `make gazelle` to update bazel (this assumes you already have bazel installed).

**Comment by rochacon** [comment]
@mikesplain oops, didn't know that, thanks. It is done. Hope build get green now 🤞

**Comment by mikesplain** [comment]
Thanks so much @rochacon! This looks great and worked well for me.  I'll approve this and cherry-pick it into 1.15 for the next release.

Thanks!

/lgtm
/approve

**Comment by rochacon** [comment]
Awesome, thanks @mikesplain!
