### PR TITLE
recheck floatingip after server is active

### LINKED ISSUE #6429: openstack will associate useless floatingips
**1. What `kops` version are you running? The command `kops version`, will display
 this information.**

kops master

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**

1.11.6

**3. What cloud provider are you using?**

openstack

**4. What commands did you run?  What is the simplest way to reproduce this issue?**

```
% openstack floating ip list
+--------------------------------------+---------------------+------------------+--------------------------------------+--------------------------------------+----------------------------------+
| ID                                   | Floating IP Address | Fixed IP Address | Port                                 | Floating Network                     | Project                          |
+--------------------------------------+---------------------+------------------+--------------------------------------+--------------------------------------+----------------------------------+
| 29883b66-733b-4c0a-8ce1-9e1ae13cc2f8 | zz.yy.xx.75       | 10.1.32.13       | 5d1d3d2a-9fd6-4d0e-81b2-5610b7e3d9d7 | ddc1377d-f60a-4df7-8356-be111271599f | ef26c7c69ceb4ef3b8f2ab9837bee574 |
| 7d27383a-3e40-4046-97d3-daefb62bd879 | zz.yy.xx.121      | 10.1.8.7         | 986c4890-6ee7-4114-80f4-c1b1629082df | ddc1377d-f60a-4df7-8356-be111271599f | ef26c7c69ceb4ef3b8f2ab9837bee574 |
+--------------------------------------+---------------------+------------------+--------------------------------------+--------------------------------------+----------------------------------+

% openstack server list
+--------------------------------------+-------------------------------+--------+----------------------------------------+--------------------------+-----------+
| ID                                   | Name                          | Status | Networks                               | Image                    | Flavor    |
+--------------------------------------+-------------------------------+--------+----------------------------------------+--------------------------+-----------+
| 2efe0513-07df-46a7-b317-62713e377f6c | sre.k8s.local-nodes-3         | ACTIVE | sre.k8s.local=10.1.8.12                | debian-9-openstack-amd64 | m1.medium |
| 51875385-7989-4d78-aeec-478fd94d7fff | sre.k8s.local-nodes-2         | ACTIVE | sre.k8s.local=10.1.8.19                | debian-9-openstack-amd64 | m1.medium |
| 716eabf8-0526-431b-805a-7eb1218a622e | sre.k8s.local-nodes-1         | ACTIVE | sre.k8s.local=10.1.8.9                 | debian-9-openstack-amd64 | m1.medium |
| 911b4d5d-10c9-4df7-868f-0aec8ebaa81e | sre.k8s.local-master-zone-2-1 | ACTIVE | sre.k8s.local=10.1.8.6                 | debian-9-openstack-amd64 | m1.medium |
| bd0933e7-009e-47da-8a9d-ff1f66a3a674 | sre.k8s.local-master-zone-1-1 | ACTIVE | sre.k8s.local=10.1.8.10                | debian-9-openstack-amd64 | m1.medium |
| 71584383-78ed-4c24-9962-55f13c6fa5e1 | sre.k8s.local-master-zone-3-1 | ACTIVE | sre.k8s.local=10.1.8.15                | debian-9-openstack-amd64 | m1.medium |
| e1ed8da0-2e8f-4c9f-9d19-963744d4edbf | sre.k8s.local-bastions-1      | ACTIVE | sre.k8s.local=10.1.8.7, zz.yy.xx.121 | debian-9-openstack-amd64 | m1.micro  |
+--------------------------------------+-------------------------------+--------+----------------------------------------+--------------------------+-----------+

% openstack server list |grep -v ID |grep -e "\d" |awk '{print $2}' | while read -r line;do openstack server delete $line ; done

% openstack server list
(empty)
```

floatingips and ports are still there. 

Then recreate machines:

```
% kops update cluster --name sre.k8s.local --yes
... snip

W0201 09:22:29.968534   94857 executor.go:130] error running task "FloatingIP/fip-sre.k8s.local-bastions-1" (9m11s remaining to succeed): Failed to associated floating IP to instance fip-sre.k8s.local-bastions-1: Bad request with: [POST https://api.company.com:13774/v2.1/servers/24033ff4-5a1f-4e24-9679-441adb2bee22/action], error message: {"badRequest": {"message": "Cannot associate floating IP zz.yy.xx.98 (f029ba47-91a5-4439-88bd-8f677201c9a8) with port 986c4890-6ee7-4114-80f4-c1b1629082df using fixed IP 10.1.8.7, as that fixed IP already has a floating IP on external network ddc1377d-f60a-4df7-8356-be111271599f.\nNeutron server returns request_ids: ['req-f33931bb-acbf-423a-afcc-2de204458a0d']", "code": 400}}
...


% openstack floating ip list
+--------------------------------------+---------------------+------------------+--------------------------------------+--------------------------------------+----------------------------------+
| ID                                   | Floating IP Address | Fixed IP Address | Port                                 | Floating Network                     | Project                          |
+--------------------------------------+---------------------+------------------+--------------------------------------+--------------------------------------+----------------------------------+
| 29883b66-733b-4c0a-8ce1-9e1ae13cc2f8 | zz.yy.xx.75       | 10.1.32.13       | 5d1d3d2a-9fd6-4d0e-81b2-5610b7e3d9d7 | ddc1377d-f60a-4df7-8356-be111271599f | ef26c7c69ceb4ef3b8f2ab9837bee574 |
| 7d27383a-3e40-4046-97d3-daefb62bd879 | zz.yy.xx.121      | 10.1.8.7         | 986c4890-6ee7-4114-80f4-c1b1629082df | ddc1377d-f60a-4df7-8356-be111271599f | ef26c7c69ceb4ef3b8f2ab9837bee574 |
| f029ba47-91a5-4439-88bd-8f677201c9a8 | zz.yy.xx.98       | None             | None                                 | ddc1377d-f60a-4df7-8356-be111271599f | ef26c7c69ceb4ef3b8f2ab9837bee574 |
+--------------------------------------+---------------------+------------------+--------------------------------------+--------------------------------------+----------------------------------+

```

**5. What happened after the commands executed?**

It created floatingip that it is not going to use

**6. What did you expect to happen?**

I expect that it could use existing ip address if there is ip already. This should be done here I think https://github.com/kubernetes/kops/blob/master/pkg/model/openstackmodel/servergroup.go#L116 (or maybe better place for that is floatingiptask? Check does port already have floatingip? if not -> create floatingip and associate, if yes -> do not anything)

/kind bug
/sig openstack

### PR DESCRIPTION
**Pull request by zetaab**
fixes #6429 

/sig openstack

### CODE REVIEW

File: upup/pkg/fi/cloudup/openstacktasks/floatingip.go [hunk 1]
```diff
@@ -189,6 +189,21 @@ func (f *FloatingIP) RenderOpenstack(t *openstack.OpenstackAPITarget, a, e, chan
 			if err := e.Server.WaitForStatusActive(t); err != nil {
 				return fmt.Errorf("Failed to associate floating IP to instance %s", *e.Name)
 			}
+
+			// recheck is there floatingip already in port
+			// this can happen for instance when recreating bastion host
```
Comment (drekle) [inline upup/pkg/fi/cloudup/openstacktasks/floatingip.go]: how is the bastion host being recreated?

Comment (zetaab) [reply upup/pkg/fi/cloudup/openstacktasks/floatingip.go]: if you run rolling-update for instance, it will delete machine (and then some another component will recreate it).

Comment (zetaab) [reply upup/pkg/fi/cloudup/openstacktasks/floatingip.go]: the problem is that gophercloud will not return port id for floatingip (openstack api will return that but its not added to gophercloud). Otherwise we could check already before renderopenstack.

Comment (drekle) [reply upup/pkg/fi/cloudup/openstacktasks/floatingip.go]: I believe that this would be making a change for a component that doesn't exist yet in master.

Comment (zetaab) [reply upup/pkg/fi/cloudup/openstacktasks/floatingip.go]: this could be managed by port task, we could just define do we need floatingip for port. Then porttask will create that if needed?

Comment (drekle) [reply upup/pkg/fi/cloudup/openstacktasks/floatingip.go]: I struggle with the compounded resources.  I like the idea of a task failing and being 1-to-1 with a resource.  I've even created resources that don't exist like poolassociation to make life easier here because I've had so much issue with doing multiple operations per task.

I'm going to test this by deleting my bastion server and re-running update.

**Comment by zetaab** [comment]
@drekle can you review and add lgtm if ok
