### PR TITLE
Don't download container runtime assets when skipping the installation

### LINKED ISSUE #15558: containerd/runc assets are still downloaded if skipInstall is true
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.26.4

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
1.26.6

**3. What cloud provider are you using?**
AWS/Spotinst

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
Have a cluster with `.spec.containerd.skipInstall = true`.

**5. What happened after the commands executed?**
The node logs indicate that containerd and runc assets are downloaded and extracted. They are never used.

**6. What did you expect to happen?**
For this to not happen

### PR DESCRIPTION
**Pull request by hakman**
For now, this only works when `SkipInstall=true` is set at cluster level.

Closes #15558

### CODE REVIEW

File: upup/pkg/fi/cloudup/apply_cluster.go [hunk 1]
```diff
@@ -1072,37 +1071,49 @@ func (c *ApplyClusterCmd) addFileAssets(assetBuilder *assets.AssetBuilder) error
...
+				break
+			}
+
+			dockerAssetUrl, dockerAssetHash, err := findDockerAsset(c.Cluster, assetBuilder, arch)
+			if err != nil {
+				return err
+			}
+			if dockerAssetUrl != nil && dockerAssetHash != nil {
+				c.Assets[arch] = append(c.Assets[arch], mirrors.BuildMirroredAsset(dockerAssetUrl, dockerAssetHash))
+			}
```
Comment (johngmyers) [inline upup/pkg/fi/cloudup/apply_cluster.go:1094]: In the future, it might be worth extracting this out to a method, possibly a reciever on `assetBuilder`. The method would take a `func(Cluster, assetBuillder, arch) (url, hash, error)`

**Review by johngmyers — APPROVED** [review]

File: upup/pkg/fi/cloudup/apply_cluster.go (hunk 1 above)
Comment (hakman) [reply upup/pkg/fi/cloudup/apply_cluster.go:1094]: Yep, should be pretty easy.
