### PR TITLE
Fix hardcoded ARN partitions

### LINKED ISSUE #12633: Partition "aws" is not valid for resource "arn:aws:ec2:*:*:volume/*".
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
Version 1.22.1 (git-da710c931fbfe0fc8fe7bb3e2d41ba6e09c899f9)

**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
 a `kops` flag.**
v1.19.10

**3. What cloud provider are you using?**
AWS

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
kops update cluster --name "${CLUSTER}" --yes

**5. What happened after the commands executed?**
W1029 09:12:44.231840   50788 executor.go:139] error running task "IAMRolePolicy/masters.admin.us-gov-west-1.gov.xxx.us.k8s.local" (9m58s remaining to succeed): error creating/updating IAMRolePolicy: MalformedPolicyDocument: Partition "aws" is not valid for resource "arn:aws:ec2:*:*:volume/*".

**6. What did you expect to happen?**
The cluster to be updated.

**7. Please provide your cluster manifest. Execute
  `kops get --name my.example.com -o yaml` to display your cluster manifest.
  You may want to remove your cluster name and other sensitive information.**

```yaml
```

**8. Please run the commands with most verbose logging by adding the `-v 10` flag.
  Paste the logs into this report, or in a gist and provide the gist link here.**

**9. Anything else do we need to know?**
The error appears to come from iamrolepolicy.go (line 282)
I can see the arn referenced in iam_builder.go (line 978)

Line 979 would need changing too as it references "arn:aws:ec2:*:*:snapshot/*"
Line 999 and 1000 also require changing as there are references to:
"arn:aws:ec2:*:*:volume/*",
"arn:aws:ec2:*:*:snapshot/*"

### PR DESCRIPTION
**Pull request by rifelpet**
IAMBuilder was hardcoding the partition in ARNs to `aws` in IAM Policy documents for OIDC Providers, EBS Volumes, and EBS Snapshots. This fixes them to use the current partition (`aws-test` in integration tests). This also fixes a few ARNs generated in cloudmock and updates any ARNs referenced in cluster manifests as well.

The end goal is that there are no ARNs with `aws` partitions in any of the integration test inputs or outputs so they can be validated for support for alternative partitions via #12635.

Fixes #12633

### CODE REVIEW

File: pkg/model/components/addonmanifests/awscloudcontrollermanager/iam.go [hunk 1]
```diff
@@ -32,7 +32,7 @@ var _ iam.Subject = &ServiceAccount{}
 func (r *ServiceAccount) BuildAWSPolicy(b *iam.PolicyBuilder) (*iam.Policy, error) {
 	clusterName := b.Cluster.ObjectMeta.Name
 	p := iam.NewPolicy(clusterName)
-	iam.AddCCMPermissions(p, b.Cluster.Spec.Networking.Kubenet != nil)
+	iam.AddCCMPermissions(p, b.Partition, b.Cluster.Spec.Networking.Kubenet != nil)
```
Comment (johngmyers) [inline pkg/model/components/addonmanifests/awscloudcontrollermanager/iam.go:35]: Would it make sense to pass the partition into `NewPolicy()` instead of having to pass it to every `Add*Permissions()` call?

**Review by johngmyers — APPROVED** [review]
